'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { StoredAppSettings } from '@/lib/app-settings'

export type AppLocale = 'en' | 'pt-BR' | 'fr'

type TranslationParams = Record<string, string | number>

type LocaleContextValue = {
  locale: AppLocale
  setLocale: (locale: AppLocale) => void
  t: (key: string, params?: TranslationParams) => string
}

const DEFAULT_LOCALE: AppLocale = 'en'

const translations = {
  en: {
    nav: {
      home: 'Home',
      search: 'Search',
      libraries: 'Libraries',
      reader: 'Reader',
      references: 'References',
      notes: 'Notes',
      maps: 'Maps',
      metadata: 'Metadata',
      reports: 'Reports',
      libraryGroup: 'Libraries',
      researchWorkspace: 'Research workspace',
      expandSidebar: 'Expand sidebar',
      collapseSidebar: 'Collapse sidebar',
    },
    topBar: {
      searchPlaceholder: 'Search',
      command: 'Command',
      toggleTheme: 'Toggle theme',
      openSettings: 'Open settings',
    },
    commandBar: {
      placeholder: 'Type a command or search...',
      empty: 'No local results found.',
      navigation: 'Navigation',
      actions: 'Actions',
      libraries: 'Libraries',
      recentDocuments: 'Recent Documents',
      toggleTheme: 'Toggle theme',
      openSettings: 'Open settings',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Drop PDFs to import',
      dropDescription: 'REFX will open Libraries and continue the import there.',
    },
    appProvider: {
      loadingWorkspace: 'Loading workspace...',
      welcomeTitle: 'Welcome to REFX',
      welcomeDescription: 'Set your name so the workspace can personalize your dashboard.',
      yourName: 'Your name',
      namePlaceholder: 'Enter your name',
      dontAskAgain: "Don't ask me again",
      continueWithoutName: 'Continue without a name',
      continue: 'Continue',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Preferences for this device.',
      adjustLocalBehavior: 'Adjust local behavior.',
      general: 'General',
      display: 'Display',
      processing: 'Processing',
      data: 'Data',
      about: 'About',
      profileTitle: 'Profile',
      profileDescription: 'Name used across your workspace.',
      yourName: 'Your Name',
      yourNamePlaceholder: 'Enter your name',
      yourNameHelp: 'Leave this blank if you prefer an impersonal greeting. You can change it anytime.',
      language: 'Language',
      appearanceTitle: 'Appearance',
      appearanceDescription: 'Appearance for this device.',
      theme: 'Theme',
      fontSize: 'Font Size',
      appUpdates: 'App Updates',
      appUpdatesDescription: 'Check for signed releases published on GitHub.',
      checkAutomatically: 'Check automatically',
      checkAutomaticallyHelp: 'Look for updates when REFX starts.',
      checking: 'Checking...',
      checkForUpdates: 'Check for Updates',
      downloadInstall: 'Download & Install',
      latestVersion: 'You are on the latest version.',
      updateAvailable: 'Refx {version} is available.',
      unableToCheckForUpdates: 'Unable to check for updates.',
      preparingUpdate: 'Preparing update...',
      updateInstallFailed: 'Update install failed.',
    },
    updateDialog: {
      title: 'Update available',
      descriptionVersion: 'Refx {version} is ready to install.',
      descriptionFallback: 'A new version of Refx is available.',
      published: 'Published {value}',
      releaseNotes: 'Release notes',
      noNotes: 'No release notes were provided.',
      later: 'Later',
      installing: 'Installing...',
      downloadInstall: 'Download & Install',
      downloading: 'Downloading update...',
      downloadingKb: 'Downloading update... {size} KB',
      installingStatus: 'Installing update...',
      restarting: 'Restarting...',
    },
    home: {
      totalDocuments: 'Total Documents',
      quickActions: 'Quick Actions',
      recentActivity: 'Recent Activity',
      noActivity: 'No activity yet',
      noActivityDescription: 'Import documents, add notes, or create highlights to build your activity feed.',
      openLibraries: 'Open Libraries',
      libraryCreated: 'Library created',
      documentAdded: 'Document added to library',
      noteCreated: 'Note created',
      highlightCreated: 'Highlight created',
      annotationCreated: 'Annotation created',
      finishedReading: 'Finished reading',
      untitledNote: 'Untitled note',
      libraryFallback: 'Library',
      page: 'Page {page}',
      minutesAgo: '{count}m ago',
      hoursAgo: '{count}h ago',
      daysAgo: '{count}d ago',
      welcomeBackNamed: 'Welcome back, {name}',
      ideasTodayNamed: 'What are your ideas today, {name}?',
      goodToSeeNamed: 'Good to see you again, {name}',
      exploringTodayNamed: 'What are you exploring today, {name}?',
      backAtItNamed: 'Back at it, {name}',
      attentionTodayNamed: 'What deserves your attention today, {name}?',
      moveForwardNamed: 'What would you like to move forward today, {name}?',
      welcomeBack: 'Welcome back',
      ideasToday: 'What are your ideas today?',
      goodToSee: 'Good to see you again',
      exploringToday: 'What are you exploring today?',
      backAtIt: 'Back at it',
      attentionToday: 'What deserves your attention today?',
      moveForwardToday: 'What would you like to move forward today?',
    },
    libraries: {
      allLibraries: 'All Libraries',
      search: 'Search',
      filters: 'Filters',
      library: 'Library',
      import: 'Import',
      importing: 'Importing...',
      book: 'Book',
      noDocuments: 'No documents found',
      noDocumentsFiltered: 'Try adjusting your filters or search query.',
      noDocumentsEmpty: 'Import PDFs or register a book to get started.',
      importPdfs: 'Import PDFs',
      importingPdfs: 'Importing PDFs...',
      registerPhysicalBook: 'Register Physical Book',
      registerPhysicalBookDescription: 'Add a non-PDF book to this library so you can capture reading notes by page or chapter.',
      title: 'Title',
      authors: 'Authors',
      authorsPlaceholder: 'Comma-separated author names',
      year: 'Year',
      isbn: 'ISBN',
      publisher: 'Publisher',
      description: 'Description',
      descriptionPlaceholder: 'Optional notes or summary',
      bookPhoto: 'Book photo',
      bookPhotoDescription: 'Optional. Add a cover photo from this computer or scan a QR code to upload it from your phone.',
      noPhoto: 'No photo selected yet',
      uploadFromPc: 'Upload from PC',
      addFromPhone: 'Add from phone',
      preparingQr: 'Preparing QR...',
      removePhoto: 'Remove photo',
      scanWithPhone: 'Scan with your phone',
      sameNetwork: 'Keep the desktop app open. Your phone and computer need to be on the same local network.',
      cancel: 'Cancel',
      registering: 'Registering...',
      registerBook: 'Register Book',
      localLibrary: 'Local library',
      documentsCount: '{count} documents',
      sortAdded: 'Date Added',
      sortOpened: 'Last Opened',
      sortTitle: 'Title',
      sortAuthors: 'Authors',
      sortYear: 'Year',
      sortRating: 'Rating',
      deduplicate: 'De-duplicate',
      deduplicateDialogTitle: 'Duplicate checker',
      deduplicateDialogDescription: 'Review possible duplicates in {library} by DOI, filename, and exact file size.',
      deduplicateDialogDescriptionFallback: 'Review possible duplicates by DOI, filename, and exact file size.',
      scanningDuplicates: 'Scanning this library for duplicate matches...',
      duplicateScanFailed: 'Unable to scan duplicates right now.',
      noDuplicatesFound: 'No duplicate groups found in this library.',
      duplicateDocumentsCount: '{count} documents',
      activeFilters: '{count} filter{suffix}',
      clearFilters: 'Clear',
      hasComments: 'Has comments',
      hasNotes: 'Has notes',
      tags: 'Tags',
      noLocalTags: 'No local tags available.',
      duplicateDoi: 'DOI match',
      duplicateFilename: 'Filename match',
      duplicateFileSize: 'Exact file size match',
      duplicateFileSizeValue: '{size} bytes',
      keepDocument: 'Keep:',
      missingDoi: 'Missing DOI',
      mergeDuplicates: 'Merge duplicates',
      mergingDuplicates: 'Merging...',
      openDocument: 'Open',
      close: 'Close',
      scanning: 'Scanning...',
      rescan: 'Rescan',
      importDocuments: 'Importing documents',
      showingRange: 'Showing {start}-{end} of {total}',
    },
    documentTable: {
      favorite: 'Favorite',
      title: 'Title',
      authors: 'Authors',
      year: 'Year',
      status: 'Status',
      metadata: 'Metadata',
      comments: 'Comments',
      rating: 'Rating',
      fetchPossible: 'Fetch Possible',
      readingStatus: 'Reading Status',
      openComments: 'Open comments',
      notes: '{count} notes',
      columns: 'Columns',
      visibleColumns: 'Visible Columns',
      columnOrder: 'Column Order',
      generateSuggestions: 'Generate Suggestions',
    },
    notesPage: {
      searchNotes: 'Search notes',
      allLibraries: 'All libraries',
      sortTimestamp: 'Sort by timestamp',
      sortPage: 'Sort by page',
      newNote: 'New Note',
      unlinkedNotes: 'Unlinked Notes',
      untitledNote: 'Untitled note',
      noContent: 'No content yet.',
      noNotesForFilters: 'No notes found for the current filters.',
      standaloneNote: 'Standalone note',
      updated: 'Updated {value}',
      openBookNotes: 'Open Book Notes',
      openDetails: 'Open Details',
      openReader: 'Open In Reader',
      reset: 'Reset',
      saving: 'Saving...',
      save: 'Save',
      selectNote: 'Select a note',
      newNoteTitle: 'New note',
    },
    readerIndex: {
      emptyTitle: 'No documents to read',
      emptyDescription: 'Import PDFs and open a document to build your local reading queue.',
      goLibraries: 'Go to Libraries',
      title: 'Reader',
      subtitle: 'Continue where you left off or jump back into recent files.',
      continueReading: 'Continue Reading',
      continueLabel: 'Continue reading',
      recentlyOpened: 'Recently Opened',
      unknownAuthor: 'Unknown author',
    },
    readerView: {
      loadingPdf: 'Loading PDF...',
      openingPdf: 'Opening PDF...',
      renderingPage: 'Rendering page {page}...',
      pdfUnavailable: 'PDF unavailable.',
      importPdf: 'Import PDF...',
      runningOcr: 'Running OCR...',
      runOcr: 'Run OCR',
      search: 'Search',
      keywordOrPhrase: 'Keyword or phrase',
      previous: 'Previous',
      next: 'Next',
      noMatchesKeyword: 'No matches found for this keyword.',
      notes: 'Notes',
      cancel: 'Cancel',
      newNote: 'New Note',
      moveBalloon: 'Move Balloon',
      choosePosition: 'Choose Position',
      writeNote: 'Write your note',
      saving: 'Saving...',
      saveNote: 'Save Note',
      createNote: 'Create Note',
      notesOnPage: '{count} note{suffix} on this page',
      edit: 'Edit',
      delete: 'Delete',
      noNoteText: 'No note text yet.',
      noNotesPage: 'No notes on this page yet.',
      deleteNoteTitle: 'Delete note?',
      deleteNoteDescription: 'This will permanently remove {label} from this document.',
      deleteNoteDescriptionFallback: 'This will permanently remove this note from the document.',
      clickOrDrawNote: 'Click or draw a box to place a note',
      drawHighlight: 'Draw a box to highlight',
      exactRegion: 'Exact region highlight',
      pageFallback: 'Page-level fallback',
      occurrence: 'Occurrence {index}',
      approxPage: 'Approx page',
    },
    metadataPage: {
      workspace: 'Metadata workspace',
      title: 'Metadata',
      subtitle: 'Review DOI-based matches and bulk-fix incomplete documents by library.',
      back: 'Back',
      library: 'Library',
      selectLibrary: 'Select a library',
      fetchPossible: 'Fetch Possible',
      missing: 'Missing',
      noLibrary: 'No library selected',
      noLibraryDescription: 'Choose a library to start reviewing metadata.',
      noFetchQueue: 'No DOI-based metadata queue',
      noMissingQueue: 'No missing-metadata queue',
      openDetails: 'Open full details',
      save: 'Save',
      saving: 'Saving...',
      doiReview: 'DOI Match Review',
      doiReviewDescription: 'Review DOI-based candidates and choose the best result.',
      manualReview: 'Manual Review',
      manualReviewDescription: 'Use the arrows to move through documents that still need manual metadata cleanup.',
      refresh: 'Refresh',
      searching: 'Searching...',
      searchAcrossProviders: 'Searching by DOI across Semantic Scholar, OpenAlex, and Crossref...',
      noCandidates: 'No metadata candidates found for this DOI.',
      fillMissing: 'Fill Missing Fields',
      applyCandidate: 'Apply Candidate',
      manualQueueHelp: 'This queue is focused on manual cleanup. Use the fields on the left, then save and move to the next document.',
    },
    searchPage: {
      title: 'Search',
      subtitle: 'Indexed full-library search backed by the local MiniSearch index.',
      subtitleCompact: 'Search across your library.',
      advancedFilters: 'Advanced Filters',
      advancedFiltersDescription: 'Build grouped keyword queries with AND and OR logic, then run them across the selected library scope.',
      advancedFiltersCompact: 'Search mode, filters, and matching rules.',
      queryMode: 'Query mode',
      queryModeHelp: 'Simple is best for quick searches. Complex lets you build grouped phrase queries.',
      simple: 'Simple',
      complex: 'Complex',
      keywordQuery: 'Keyword query',
      keywordQueryHelp: 'Simple search supports quoted phrases. In complex search, each keyword is treated as one phrase.',
      addGroup: 'Add group',
      quickSearch: 'Quick search',
      quickSearchPlaceholder: 'Search the local full-text index',
      search: 'Search',
      simpleHelp: 'Press Enter or Search to run. Use quotes for exact phrases, like "historia cronicas".',
      betweenGroups: 'Between groups',
      everyGroup: 'A document must satisfy every group.',
      anyGroup: 'A document can satisfy any one of the groups.',
      group: 'Group {index}',
      addKeywordPlaceholder: 'Add a keyword to this group',
      add: 'Add',
      addKeywordsHelpAnd: 'Add one or more keywords. Each keyword is treated as one phrase, and this group matches when every keyword phrase is found.',
      addKeywordsHelpOr: 'Add one or more keywords. Each keyword is treated as one phrase, and this group matches when any keyword phrase is found.',
      flexibility: 'Flexibility',
      strict: 'Strict',
      balanced: 'Balanced',
      flexible: 'Flexible',
      veryFlexible: 'Very flexible',
      flexibilityHelp: 'Higher flexibility allows closer variants such as misspellings, broken words across line wraps, and near matches.',
      library: 'Library',
      readingStage: 'Reading stage',
      anyStage: 'Any stage',
      metadataQuality: 'Metadata quality',
      anyStatus: 'Any status',
      favoritesOnly: 'Showing favorites only',
      filterFavorites: 'Filter to favorites',
      persistentSearch: 'Persistent indexed search',
      searchingDocs: 'Searching {processed}/{total} documents for {query}',
      resultsFor: '{count} result{suffix} for {query}',
      searchingBadge: 'Searching',
      startTitle: 'Start a Search',
      startDescriptionSimple: 'Type into the search box to query your local indexed library.',
      startDescriptionComplex: 'Add one or more keyword groups and press Search to scan your full library.',
      loadingFallback: 'Querying the local MiniSearch index and resolving snippets from stored extracted text.',
      noMatchesTitle: 'No matching documents',
      noMatchesDescription: 'Try increasing flexibility or broadening the filters.',
      unknownAuthor: 'Unknown author',
      page: 'Page {page}',
      openReader: 'Open in Reader',
      openDetails: 'Open Details',
      exactRegion: 'Exact region highlight',
      pageFallback: 'Page-level fallback',
      occurrence: 'Occurrence {index}',
      approxPage: 'Approx page',
      noMatchesForKeyword: 'No matches found for this keyword.',
      preparingIndex: 'Preparing the local search index...',
      resultsReady: '{count} result{suffix} ready',
    },
    mapsPage: {
      title: 'Maps',
      subtitle: 'Explore relationships, shape saved views, and build links directly on the canvas.',
      workspace: 'Workspace',
      workingMap: 'Working map',
      workingMapDescription: 'Choose a saved view or keep arranging the current working map.',
      mapView: 'Map view',
      canvasEditor: 'Canvas editor',
      addReferencedDocument: 'Add referenced document',
      addCitingDocument: 'Add citing document',
      addDocument: 'Add a document',
      addDocumentHelp: 'Search the current library and bring another document into this map.',
      addDocumentLinkHelp: 'Search the library, add the document to the canvas, and connect it in one step.',
      findReferencedDocument: 'Find referenced document',
      findCitingDocument: 'Find citing document',
      addDocumentToMap: 'Add document to map',
      myWork: 'My work',
      noDocumentsControls: 'No documents match the current controls.',
      noLinksControls: 'No links match the current controls.',
      saveGraphView: 'Save Graph View',
      saveGraphViewDescription: 'Persist the current map as a reusable research workspace with its current filters, subset, and layout.',
      editGraphView: 'Edit Graph View',
      editGraphViewDescription: 'Rename this workspace or update its description without changing the underlying document relations.',
      cancel: 'Cancel',
      saveView: 'Save View',
      saveChanges: 'Save Changes',
      saveAsNewView: 'Save as new view',
      saveCurrentView: 'Save changes',
      saveCurrentViewHelp: 'Update the currently selected saved view',
      saveNewViewHelp: 'Save this layout and filter setup as a reusable map view',
      rebuildLayout: 'Rebuild layout',
      rebuildLayoutHelp: 'Re-space the visible nodes to improve the layout',
      showControls: 'Show controls',
      hideControls: 'Hide controls',
      renameView: 'Rename view',
      duplicateView: 'Duplicate',
      resetLayout: 'Reset layout',
      resetLayoutHelp: 'Reset node positions in this saved view',
      delete: 'Delete',
      addMyWork: 'Add "my work"',
      addMyWorkDescription: 'Create a map node for your own work. It is saved in the library and can make references to other documents.',
      addToMap: 'Add to map',
      workName: 'Work name',
      workNamePlaceholder: 'My article draft',
      name: 'Name',
      workspaceNote: 'Workspace note',
      workspaceNotePlaceholder: 'Why this map exists, what this subset means, or what to review next.',
      searchDocumentsPlaceholder: 'Search documents...',
      searchAndLinkPlaceholder: 'Search and add a document to link...',
      noMatchingDocument: 'No matching document found.',
      selectReferenceTarget: 'Select the document this one makes reference to, or search to add it',
      selectCitationTarget: 'Select the document that references this one, or search to add it',
      deleteNode: 'Delete node',
      deleteAllLinks: 'Delete all links',
      removeLinkMenu: 'Remove link',
      invertLinkMenu: 'Invert link',
      relationDetails: 'Relationship Details',
      relationDetailsDescription: 'Select a document node to inspect it, or click a connection to review or remove that relation.',
      relation: 'Relation',
      relationDescription: 'Review this persisted link between two documents.',
      closeDetails: 'Close details',
      citingDocument: 'Citing document',
      referencedDocument: 'Referenced document',
      makesReferenceTo: 'Makes reference to',
      isReferencedBy: 'Is referenced by',
      reverseLinkDirection: 'Reverse Link Direction',
      reverseLinkDirectionHelp: 'Swap which document points to the other',
      removeLink: 'Remove Link',
      removeLinkHelp: 'Delete this connection from the map',
      physicalBook: 'Physical book',
      myWorkType: 'My work',
      pdfDocument: 'PDF document',
      author: 'Author',
      abstract: 'Abstract',
      collapse: 'Collapse',
      expand: 'Expand',
      none: 'none',
      addOrConnect: 'Add or connect linked documents',
      addReference: 'Add reference',
      addReferenceHelp: 'Link this document to one it references',
      addCitation: 'Add citation',
      addCitationHelp: 'Link a document that cites this one',
      findDocument: 'Find document',
      findDocumentHelp: 'Search this map and jump to a matching node.',
      searchTitlesInMap: 'Search titles in this map',
      jumpToMatchingDocument: 'Jump to matching document',
      filterLayout: 'Filters & Layout',
      filterLayoutHelp: 'Show graph filters, layout options, and quick view tools',
      expandControls: 'Expand',
      collapseControls: 'Collapse',
      appearance: 'Appearance',
      appearanceDescription: 'Control how documents look in the graph.',
      nodeColors: 'Node colors',
      libraryColors: 'Library',
      yearColors: 'Year',
      density: 'Density',
      status: 'Status',
      component: 'Component',
      nodeSize: 'Node size',
      uniform: 'Uniform',
      inboundCitations: 'Inbound citations',
      totalDegree: 'Total degree',
      focus: 'Focus',
      focusDescription: 'Limit the view around the selected document when needed.',
      focusType: 'Focus type',
      fullGraph: 'Full graph',
      oneHopNeighbors: '1-hop neighbors',
      twoHopNeighbors: '2-hop neighbors',
      hideIsolated: 'Hide isolated documents',
      hideIsolatedDescription: 'Remove documents with no visible links.',
      years: 'Years',
      yearsDescription: 'Narrow the visible documents by publication year.',
      from: 'From',
      to: 'To',
      any: 'Any',
    },
    metadataFields: {
      title: 'Title',
      authors: 'Authors',
      year: 'Year',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Publisher',
      citationKey: 'Citation key',
      abstract: 'Abstract',
      untitledDocument: 'Untitled document',
      queuePosition: '{current} of {total}',
      allCompleteDescription: 'All DOI-backed documents in {library} already look complete.',
      noMissingDescription: 'No documents without DOI-based fetch options are waiting in {library}.',
    },
    common: {
      unread: 'Unread',
      reading: 'Reading',
      finished: 'Finished',
      missing: 'Missing',
      partial: 'Partial',
      complete: 'Complete',
      ocrPending: 'OCR Pending',
      processing: 'Processing',
      ocrComplete: 'OCR Complete',
      ocrFailed: 'OCR Failed',
      nativeText: 'Native Text',
      new: 'NEW',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },
  'pt-BR': {
    nav: {
      home: 'Início',
      search: 'Busca',
      libraries: 'Bibliotecas',
      reader: 'Leitor',
      references: 'Referências',
      notes: 'Notas',
      maps: 'Mapas',
      metadata: 'Metadados',
      reports: 'Relatórios',
      libraryGroup: 'Bibliotecas',
      researchWorkspace: 'Espaço de pesquisa',
      expandSidebar: 'Expandir barra lateral',
      collapseSidebar: 'Recolher barra lateral',
    },
    topBar: {
      searchPlaceholder: 'Buscar',
      command: 'Comandos',
      toggleTheme: 'Alternar tema',
      openSettings: 'Abrir configurações',
    },
    commandBar: {
      placeholder: 'Digite um comando ou pesquise...',
      empty: 'Nenhum resultado local encontrado.',
      navigation: 'Navegação',
      actions: 'Ações',
      libraries: 'Bibliotecas',
      recentDocuments: 'Documentos recentes',
      toggleTheme: 'Alternar tema',
      openSettings: 'Abrir configurações',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Solte PDFs para importar',
      dropDescription: 'O REFX abrirá Bibliotecas e continuará a importação lá.',
    },
    appProvider: {
      loadingWorkspace: 'Carregando espaço de trabalho...',
      welcomeTitle: 'Bem-vindo ao REFX',
      welcomeDescription: 'Defina seu nome para personalizar o painel.',
      yourName: 'Seu nome',
      namePlaceholder: 'Digite seu nome',
      dontAskAgain: 'Não perguntar novamente',
      continueWithoutName: 'Continuar sem nome',
      continue: 'Continuar',
    },
    settings: {
      title: 'Configurações',
      subtitle: 'Preferências deste dispositivo.',
      adjustLocalBehavior: 'Ajuste o comportamento local.',
      general: 'Geral',
      display: 'Aparência',
      processing: 'Processamento',
      data: 'Dados',
      about: 'Sobre',
      profileTitle: 'Perfil',
      profileDescription: 'Nome usado em seu espaço de trabalho.',
      yourName: 'Seu nome',
      yourNamePlaceholder: 'Digite seu nome',
      yourNameHelp: 'Deixe em branco se preferir uma saudação impessoal. Você pode mudar isso depois.',
      language: 'Idioma',
      appearanceTitle: 'Aparência',
      appearanceDescription: 'Aparência deste dispositivo.',
      theme: 'Tema',
      fontSize: 'Tamanho da fonte',
      appUpdates: 'AtualizaÃ§Ãµes do app',
      appUpdatesDescription: 'Verifique versões assinadas publicadas no GitHub.',
      checkAutomatically: 'Verificar automaticamente',
      checkAutomaticallyHelp: 'Procurar atualizações quando o REFX iniciar.',
      checking: 'Verificando...',
      checkForUpdates: 'Verificar atualizações',
      downloadInstall: 'Baixar e instalar',
      latestVersion: 'Você está na versãp mais recente.',
      updateAvailable: 'Refx {version} está disponí­vel.',
      unableToCheckForUpdates: 'Não foi possí­vel verificar atualizações.',
      preparingUpdate: 'Preparando atualização...',
      updateInstallFailed: 'A instalação da atualização falhou.',
    },
    updateDialog: {
      title: 'Atualização disponível',
      descriptionVersion: 'Refx {version} está pronto para instalar.',
      descriptionFallback: 'Uma nova versão do Refx está disponí­vel.',
      published: 'Publicado {value}',
      releaseNotes: 'Notas da versão',
      noNotes: 'Nenhuma nota de versão foi fornecida.',
      later: 'Mais tarde',
      installing: 'Instalando...',
      downloadInstall: 'Baixar e instalar',
      downloading: 'Baixando atualização...',
      downloadingKb: 'Baixando atualização... {size} KB',
      installingStatus: 'Instalando atualização...',
      restarting: 'Reiniciando...',
    },
    home: {
      totalDocuments: 'Total de documentos',
      quickActions: 'Ações rápidas',
      recentActivity: 'Atividade recente',
      noActivity: 'Ainda não há atividade',
      noActivityDescription: 'Importe documentos, adicione notas ou crie destaques para montar seu feed de atividade.',
      openLibraries: 'Abrir Bibliotecas',
      libraryCreated: 'Biblioteca criada',
      documentAdded: 'Documento adicionado a biblioteca',
      noteCreated: 'Nota criada',
      highlightCreated: 'Destaque criado',
      annotationCreated: 'Anotação criada',
      finishedReading: 'Leitura concluída',
      untitledNote: 'Nota sem título',
      libraryFallback: 'Biblioteca',
      page: 'Página {page}',
      minutesAgo: 'há {count} min',
      hoursAgo: 'há {count} h',
      daysAgo: 'há {count} d',
      welcomeBackNamed: 'Bem-vindo de volta, {name}',
      ideasTodayNamed: 'Quais são suas ideias hoje, {name}?',
      goodToSeeNamed: 'Bom ver você novamente, {name}',
      exploringTodayNamed: 'O que voce está explorando hoje, {name}?',
      backAtItNamed: 'De volta ao trabalho, {name}',
      attentionTodayNamed: 'O que merece sua atenção hoje, {name}?',
      moveForwardNamed: 'No que você quer trabalhar hoje, {name}?',
      welcomeBack: 'Bem-vindo de volta',
      ideasToday: 'Quais são suas ideias hoje?',
      goodToSee: 'Bom ver você novamente',
      exploringToday: 'O que você esta explorando hoje?',
      backAtIt: 'De volta ao trabalho',
      attentionToday: 'O que merece sua atenção hoje?',
      moveForwardToday: 'O que voce quer avançar hoje?',
    },
    libraries: {
      allLibraries: 'Todas as bibliotecas',
      search: 'Buscar',
      filters: 'Filtros',
      library: 'Biblioteca',
      import: 'Importar',
      importing: 'Importando...',
      book: 'Livro',
      noDocuments: 'Nenhum documento encontrado',
      noDocumentsFiltered: 'Tente ajustar os filtros ou a busca.',
      noDocumentsEmpty: 'Importe PDFs ou registre um livro para começar.',
      importPdfs: 'Importar PDFs',
      importingPdfs: 'Importando PDFs...',
      registerPhysicalBook: 'Registrar livro físico',
      registerPhysicalBookDescription: 'Adicione um livro não-PDF a esta biblioteca para capturar notas de leitura por página ou capítulo.',
      title: 'Título',
      authors: 'Autores',
      authorsPlaceholder: 'Nomes dos autores separados por vírgula',
      year: 'Ano',
      isbn: 'ISBN',
      publisher: 'Editora',
      description: 'Descrição',
      descriptionPlaceholder: 'Notas ou resumo opcionais',
      bookPhoto: 'Foto do livro',
      bookPhotoDescription: 'Opcional. Adicione uma foto da capa deste computador ou leia um QR code para enviar do telefone.',
      noPhoto: 'Nenhuma foto selecionada ainda',
      uploadFromPc: 'Enviar do PC',
      addFromPhone: 'Adicionar do telefone',
      preparingQr: 'Preparando QR...',
      removePhoto: 'Remover foto',
      scanWithPhone: 'Escaneie com o telefone',
      sameNetwork: 'Mantenha o app desktop aberto. O telefone e o computador precisam estar na mesma rede local.',
      cancel: 'Cancelar',
      registering: 'Registrando...',
      registerBook: 'Registrar livro',
      localLibrary: 'Biblioteca local',
      documentsCount: '{count} documentos',
      sortAdded: 'Data de adicao',
      sortOpened: 'Ultima abertura',
      sortTitle: 'Titulo',
      sortAuthors: 'Autores',
      sortYear: 'Ano',
      sortRating: 'Avaliacao',
      deduplicate: 'Desduplicar',
      deduplicateDialogTitle: 'Verificador de duplicados',
      deduplicateDialogDescription: 'Revise possiveis duplicados em {library} por DOI, nome do arquivo e tamanho exato do arquivo.',
      deduplicateDialogDescriptionFallback: 'Revise possiveis duplicados por DOI, nome do arquivo e tamanho exato do arquivo.',
      scanningDuplicates: 'Verificando esta biblioteca por duplicados...',
      duplicateScanFailed: 'Nao foi possivel verificar duplicados agora.',
      noDuplicatesFound: 'Nenhum grupo duplicado encontrado nesta biblioteca.',
      duplicateDocumentsCount: '{count} documentos',
      activeFilters: '{count} filtro{suffix}',
      clearFilters: 'Limpar',
      hasComments: 'Com comentários',
      hasNotes: 'Com notas',
      tags: 'Tags',
      noLocalTags: 'Nenhuma tag local disponível.',
      duplicateDoi: 'Correspondência por DOI',
      duplicateFilename: 'Correspondência por nome do arquivo',
      duplicateFileSize: 'Correspondência por tamanho exato',
      duplicateFileSizeValue: '{size} bytes',
      keepDocument: 'Manter:',
      missingDoi: 'DOI ausente',
      mergeDuplicates: 'Mesclar duplicados',
      mergingDuplicates: 'Mesclando...',
      openDocument: 'Abrir',
      close: 'Fechar',
      scanning: 'Verificando...',
      rescan: 'Verificar novamente',
      importDocuments: 'Importando documentos',
      showingRange: 'Mostrando {start}-{end} de {total}',
    },
    documentTable: {
      favorite: 'Favorito',
      title: 'Título',
      authors: 'Autores',
      year: 'Ano',
      status: 'Status',
      metadata: 'Metadados',
      comments: 'Comentários',
      rating: 'Avaliação',
      fetchPossible: 'Busca possível',
      readingStatus: 'Status de leitura',
      openComments: 'Abrir comentários',
      notes: '{count} notas',
      columns: 'Colunas',
      visibleColumns: 'Colunas visíveis',
      columnOrder: 'Ordem das colunas',
      generateSuggestions: 'Gerar sugestões',
    },
    notesPage: {
      searchNotes: 'Buscar notas',
      allLibraries: 'Todas as bibliotecas',
      sortTimestamp: 'Ordenar por data',
      sortPage: 'Ordenar por pagina',
      newNote: 'Nova nota',
      unlinkedNotes: 'Notas sem vínculo',
      untitledNote: 'Nota sem título',
      noContent: 'Sem conteúdo ainda.',
      noNotesForFilters: 'Nenhuma nota encontrada para os filtros atuais.',
      standaloneNote: 'Nota independente',
      updated: 'Atualizado {value}',
      openBookNotes: 'Abrir notas do livro',
      openDetails: 'Abrir detalhes',
      openReader: 'Abrir no leitor',
      reset: 'Redefinir',
      saving: 'Salvando...',
      save: 'Salvar',
      selectNote: 'Selecione uma nota',
      newNoteTitle: 'Nova nota',
    },
    readerIndex: {
      emptyTitle: 'Nenhum documento para ler',
      emptyDescription: 'Importe PDFs e abra um documento para montar sua fila de leitura local.',
      goLibraries: 'Ir para Bibliotecas',
      title: 'Leitor',
      subtitle: 'Continue de onde parou ou volte aos arquivos recentes.',
      continueReading: 'Continuar leitura',
      continueLabel: 'Continuar leitura',
      recentlyOpened: 'Abertos recentemente',
      unknownAuthor: 'Autor desconhecido',
    },
    readerView: {
      loadingPdf: 'Carregando PDF...',
      openingPdf: 'Abrindo PDF...',
      renderingPage: 'Renderizando pagina {page}...',
      pdfUnavailable: 'PDF indisponivel.',
      importPdf: 'Importar PDF...',
      runningOcr: 'Executando OCR...',
      runOcr: 'Executar OCR',
      search: 'Busca',
      keywordOrPhrase: 'Palavra-chave ou frase',
      previous: 'Anterior',
      next: 'Próxima',
      noMatchesKeyword: 'Nenhuma ocorrência encontrada para esta palavra-chave.',
      notes: 'Notas',
      cancel: 'Cancelar',
      newNote: 'Nova nota',
      moveBalloon: 'Mover balao',
      choosePosition: 'Escolher posicao',
      writeNote: 'Escreva sua nota',
      saving: 'Salvando...',
      saveNote: 'Salvar nota',
      createNote: 'Criar nota',
      notesOnPage: '{count} nota{suffix} nesta pagina',
      edit: 'Editar',
      delete: 'Excluir',
      noNoteText: 'Sem texto na nota ainda.',
      noNotesPage: 'Ainda não há notas nesta página.',
      deleteNoteTitle: 'Excluir nota?',
      deleteNoteDescription: 'Isso removerá permanentemente {label} deste documento.',
      deleteNoteDescriptionFallback: 'Isso removerá permanentemente esta nota do documento.',
      clickOrDrawNote: 'Clique ou desenhe uma caixa para posicionar a nota',
      drawHighlight: 'Desenhe uma caixa para destacar',
      exactRegion: 'Região exata',
      pageFallback: 'Fallback por página',
      occurrence: 'Ocorrência {index}',
      approxPage: 'Página aprox',
    },
    metadataPage: {
      workspace: 'Espao de metadados',
      title: 'Metadados',
      subtitle: 'Revise correspondências por DOI e corrija documentos incompletos por biblioteca.',
      back: 'Voltar',
      library: 'Biblioteca',
      selectLibrary: 'Selecione uma biblioteca',
      fetchPossible: 'Busca possivel',
      missing: 'Ausente',
      noLibrary: 'Nenhuma biblioteca selecionada',
      noLibraryDescription: 'Escolha uma biblioteca para comecar a revisar metadados.',
      noFetchQueue: 'Sem documentos com busca possível por DOI',
      noMissingQueue: 'Sem documentos com metadados ausentes',
      openDetails: 'Abrir detalhes',
      save: 'Salvar',
      saving: 'Salvando...',
      doiReview: 'Revisao de DOI',
      doiReviewDescription: 'Revise candidatos baseados em DOI e escolha o melhor resultado.',
      manualReview: 'Revisao manual',
      manualReviewDescription: 'Use as setas para percorrer documentos que ainda precisam de limpeza manual.',
      refresh: 'Atualizar',
      searching: 'Buscando...',
      searchAcrossProviders: 'Buscando por DOI em Semantic Scholar, OpenAlex e Crossref...',
      noCandidates: 'Nenhum candidato de metadados encontrado para este DOI.',
      fillMissing: 'Preencher ausentes',
      applyCandidate: 'Aplicar candidato',
      manualQueueHelp: 'Esta fila foca em limpeza manual. Use os campos a esquerda, salve e passe para o proximo documento.',
    },
    searchPage: {
      title: 'Busca',
      subtitle: 'Busca indexada em toda a biblioteca com MiniSearch local.',
      subtitleCompact: 'Busque em toda a sua biblioteca.',
      advancedFilters: 'Filtros avançados',
      advancedFiltersDescription: 'Monte consultas em grupos com lógica AND e OR e execute no escopo da biblioteca selecionada.',
      advancedFiltersCompact: 'Modo de busca, filtros e regras de correspondencia.',
      queryMode: 'Modo de consulta',
      queryModeHelp: 'Simples e melhor para buscas rapidas. Complexo permite montar consultas por grupos e frases.',
      simple: 'Simples',
      complex: 'Complexo',
      keywordQuery: 'Consulta por palavras-chave',
      keywordQueryHelp: 'A busca simples aceita frases entre aspas. Na busca complexa, cada palavra-chave e tratada como uma frase.',
      addGroup: 'Adicionar grupo',
      quickSearch: 'Busca rápida',
      quickSearchPlaceholder: 'Buscar',
      search: 'Buscar',
      simpleHelp: 'Pressione Enter ou Buscar. Use aspas para frases exatas.',
      betweenGroups: 'Entre grupos',
      everyGroup: 'Um documento deve satisfazer todos os grupos.',
      anyGroup: 'Um documento pode satisfazer qualquer grupo.',
      group: 'Grupo {index}',
      addKeywordPlaceholder: 'Adicionar palavra-chave a este grupo',
      add: 'Adicionar',
      addKeywordsHelpAnd: 'Adicione uma ou mais palavras-chave. Cada uma e tratada como uma frase, e o grupo so bate quando todas forem encontradas.',
      addKeywordsHelpOr: 'Adicione uma ou mais palavras-chave. Cada uma e tratada como uma frase, e o grupo bate quando qualquer uma for encontrada.',
      flexibility: 'Flexibilidade',
      strict: 'Rigorosa',
      balanced: 'Equilibrada',
      flexible: 'Flexível',
      veryFlexible: 'Muito flexível',
      flexibilityHelp: 'Maior flexibilidade permite variantes próximas, erros de digitção, palavras quebradas por linha e aproximações.',
      library: 'Biblioteca',
      readingStage: 'Status de leitura',
      anyStage: 'Qualquer status',
      metadataQuality: 'Qualidade dos metadados',
      anyStatus: 'Qualquer status',
      favoritesOnly: 'Mostrando apenas favoritos',
      filterFavorites: 'Filtrar favoritos',
      persistentSearch: 'Busca indexada persistente',
      searchingDocs: 'Buscando {processed}/{total} documentos por {query}',
      resultsFor: '{count} resultado{suffix} para {query}',
      searchingBadge: 'Buscando',
      startTitle: 'Inicie uma busca',
      startDescriptionSimple: 'Digite na caixa de busca para consultar sua biblioteca local indexada.',
      startDescriptionComplex: 'Adicione um ou mais grupos e pressione Buscar para varrer a biblioteca inteira.',
      loadingFallback: 'Consultando o indice local MiniSearch e resolvendo trechos do texto extraido.',
      noMatchesTitle: 'Nenhum documento correspondente',
      noMatchesDescription: 'Tente aumentar a flexibilidade ou ampliar os filtros.',
      unknownAuthor: 'Autor desconhecido',
      page: 'Pagina {page}',
      openReader: 'Abrir no leitor',
      openDetails: 'Abrir detalhes',
      exactRegion: 'Regiao exata',
      pageFallback: 'Fallback por pagina',
      occurrence: 'Ocorrencia {index}',
      approxPage: 'Pagina aprox',
      noMatchesForKeyword: 'Nenhuma ocorrencia encontrada para esta palavra-chave.',
      preparingIndex: 'Preparando o indice local de busca...',
      resultsReady: '{count} resultado{suffix} pronto',
    },
    mapsPage: {
      title: 'Mapas',
      subtitle: 'Explore relações, organize vistas salvas e crie links direto no canvas.',
      workspace: 'Espaco de trabalho',
      workingMap: 'Mapa em andamento',
      workingMapDescription: 'Escolha uma vista salva ou continue organizando o mapa atual.',
      mapView: 'Vista do mapa',
      canvasEditor: 'Editor do mapa',
      addReferencedDocument: 'Adicionar documento referenciado',
      addCitingDocument: 'Adicionar documento citante',
      addDocument: 'Adicionar documento',
      addDocumentHelp: 'Busque na biblioteca atual e traga outro documento para este mapa.',
      addDocumentLinkHelp: 'Busque na biblioteca, adicione o documento ao mapa e conecte tudo em um unico fluxo.',
      findReferencedDocument: 'Encontrar documento referenciado',
      findCitingDocument: 'Encontrar documento citante',
      addDocumentToMap: 'Adicionar documento ao mapa',
      myWork: 'Meu trabalho',
      noDocumentsControls: 'Nenhum documento corresponde aos controles atuais.',
      noLinksControls: 'Nenhum link corresponde aos controles atuais.',
      saveGraphView: 'Salvar vista do mapa',
      saveGraphViewDescription: 'Salve o mapa atual como um espaço reutilizável com filtros, subconjunto e layout.',
      editGraphView: 'Editar vista do mapa',
      editGraphViewDescription: 'Renomeie este espaco ou atualize a descrição sem alterar as relações dos documentos.',
      cancel: 'Cancelar',
      saveView: 'Salvar vista',
      saveChanges: 'Salvar alteracoes',
      saveAsNewView: 'Salvar como nova vista',
      saveCurrentView: 'Salvar alterações',
      saveCurrentViewHelp: 'Atualizar a vista salva atualmente selecionada',
      saveNewViewHelp: 'Salvar este layout e conjunto de filtros como uma vista reutilizavel',
      rebuildLayout: 'Reconstruir layout',
      rebuildLayoutHelp: 'Reorganizar os nos visiveis para melhorar o layout',
      showControls: 'Mostrar controles',
      hideControls: 'Ocultar controles',
      renameView: 'Renomear vista',
      duplicateView: 'Duplicar',
      resetLayout: 'Redefinir layout',
      resetLayoutHelp: 'Redefinir as posicoes dos nos nesta vista salva',
      delete: 'Excluir',
      addMyWork: 'Adicionar "meu trabalho"',
      addMyWorkDescription: 'Crie um no para seu próprio trabalho. Ele fica salvo na biblioteca e pode fazer referencias para outros documentos.',
      addToMap: 'Adicionar ao mapa',
      workName: 'Nome do trabalho',
      workNamePlaceholder: 'Meu rascunho de artigo',
      name: 'Nome',
      workspaceNote: 'Nota do espaço',
      workspaceNotePlaceholder: 'Por que este mapa existe, o que este subconjunto significa ou o que revisar depois.',
      searchDocumentsPlaceholder: 'Buscar documentos...',
      searchAndLinkPlaceholder: 'Buscar e adicionar um documento para vincular...',
      noMatchingDocument: 'Nenhum documento correspondente encontrado.',
      selectReferenceTarget: 'Selecione o documento ao qual este faz referencia ou pesquise para adiciona-lo',
      selectCitationTarget: 'Selecione o documento que referencia este ou pesquise para adiciona-lo',
      deleteNode: 'Excluir no',
      deleteAllLinks: 'Excluir todos os links',
      removeLinkMenu: 'Remover link',
      invertLinkMenu: 'Inverter link',
      relationDetails: 'Detalhes da relação',
      relationDetailsDescription: 'Selecione um documento para inspeciona-lo ou clique em uma conexao para revisar ou remover a relacao.',
      relation: 'Relação',
      relationDescription: 'Revise este link persistido entre dois documentos.',
      closeDetails: 'Fechar detalhes',
      citingDocument: 'Documento citante',
      referencedDocument: 'Documento referenciado',
      makesReferenceTo: 'Faz referência a',
      isReferencedBy: 'É citado por',
      reverseLinkDirection: 'Inverter direção do link',
      reverseLinkDirectionHelp: 'Trocar qual documento aponta para o outro',
      removeLink: 'Remover link',
      removeLinkHelp: 'Excluir esta conexao do mapa',
      physicalBook: 'Livro físico',
      myWorkType: 'Meu trabalho',
      pdfDocument: 'Documento PDF',
      author: 'Autor',
      abstract: 'Resumo',
      collapse: 'Recolher',
      expand: 'Expandir',
      none: 'nenhum',
      addOrConnect: 'Adicionar ou conectar documentos vinculados',
      addReference: 'Adicionar referência',
      addReferenceHelp: 'Vincular este documento a outro que ele referencia',
      addCitation: 'Adicionar citação',
      addCitationHelp: 'Vincular um documento que cita este',
      findDocument: 'Encontrar documento',
      findDocumentHelp: 'Busque neste mapa e pule para um no correspondente.',
      searchTitlesInMap: 'Buscar títulos neste mapa',
      jumpToMatchingDocument: 'Ir para documento correspondente',
      filterLayout: 'Filtros e layout',
      filterLayoutHelp: 'Mostrar filtros do mapa, opções de layout e ferramentas rápidas',
      expandControls: 'Expandir',
      collapseControls: 'Recolher',
      appearance: 'Aparência',
      appearanceDescription: 'Controle como os documentos aparecem no mapa.',
      nodeColors: 'Cores dos círculos',
      libraryColors: 'Biblioteca',
      yearColors: 'Ano',
      density: 'Densidade',
      status: 'Status',
      component: 'Componente',
      nodeSize: 'Tamanho do círculo',
      uniform: 'Uniforme',
      inboundCitations: 'Citações recebidas',
      totalDegree: 'Grau total',
      focus: 'Foco',
      focusDescription: 'Limite a visualização ao redor do documento selecionado quando necessário.',
      focusType: 'Tipo de foco',
      fullGraph: 'Mapa completo',
      oneHopNeighbors: 'Conectados diretamente',
      twoHopNeighbors: 'Cotactados diretamente +1',
      hideIsolated: 'Ocultar documentos isolados',
      hideIsolatedDescription: 'Remover documentos sem links visíveis.',
      years: 'Anos',
      yearsDescription: 'Restrinja os documentos visíveis por ano de publicação.',
      from: 'De',
      to: 'Até',
      any: 'Qualquer',
    },
    metadataFields: {
      title: 'Titulo',
      authors: 'Autores',
      year: 'Ano',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Editora',
      citationKey: 'Chave de citacao',
      abstract: 'Resumo',
      untitledDocument: 'Documento sem titulo',
      queuePosition: '{current} de {total}',
      allCompleteDescription: 'Todos os documentos com DOI em {library} ja parecem completos.',
      noMissingDescription: 'Nao ha documentos sem opcao de busca por DOI aguardando em {library}.',
    },
    common: {
      unread: 'Não lido',
      reading: 'Lendo',
      finished: 'Concluído',
      missing: 'Ausente',
      partial: 'Parcial',
      complete: 'Completo',
      ocrPending: 'OCR pendente',
      processing: 'Processando',
      ocrComplete: 'OCR concluído',
      ocrFailed: 'OCR falhou',
      nativeText: 'Texto nativo',
      new: 'NOVO',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      search: 'Recherche',
      libraries: 'Bibliothèques',
      reader: 'Lecteur',
      references: 'Références',
      notes: 'Notes',
      maps: 'Cartes',
      metadata: 'Métadonnées',
      reports: 'Rapports',
      libraryGroup: 'Bibliothèques',
      researchWorkspace: 'Espace de recherche',
      expandSidebar: 'Développer la barre latérale',
      collapseSidebar: 'Réduire la barre latérale',
    },
    topBar: {
      searchPlaceholder: 'Rechercher',
      command: 'Commandes',
      toggleTheme: 'Changer de thème',
      openSettings: 'Ouvrir les paramètres',
    },
    commandBar: {
      placeholder: 'Tapez une commande ou lancez une recherche...',
      empty: 'Aucun résultat local trouvé.',
      navigation: 'Navigation',
      actions: 'Actions',
      libraries: 'Bibliothèques',
      recentDocuments: 'Documents récents',
      toggleTheme: 'Changer de thème',
      openSettings: 'Ouvrir les paramètres',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Déposez des PDF à importer',
      dropDescription: 'REFX ouvrira Bibliothèques et poursuivra l’import là-bas.',
    },
    appProvider: {
      loadingWorkspace: 'Chargement de l’espace de travail...',
      welcomeTitle: 'Bienvenue dans REFX',
      welcomeDescription: 'Définissez votre nom pour personnaliser le tableau de bord.',
      yourName: 'Votre nom',
      namePlaceholder: 'Saisissez votre nom',
      dontAskAgain: 'Ne plus demander',
      continueWithoutName: 'Continuer sans nom',
      continue: 'Continuer',
    },
    settings: {
      title: 'Paramètres',
      subtitle: 'Préférences de cet appareil.',
      adjustLocalBehavior: 'Ajustez le comportement local.',
      general: 'Général',
      display: 'Affichage',
      processing: 'Traitement',
      data: 'Données',
      about: 'À propos',
      profileTitle: 'Profil',
      profileDescription: 'Nom utilisé dans votre espace de travail.',
      yourName: 'Votre nom',
      yourNamePlaceholder: 'Saisissez votre nom',
      yourNameHelp: 'Laissez ce champ vide si vous préférez une salutation impersonnelle. Vous pouvez le modifier plus tard.',
      language: 'Langue',
      appearanceTitle: 'Apparence',
      appearanceDescription: 'Apparence de cet appareil.',
      theme: 'Thème',
      fontSize: 'Taille du texte',
      appUpdates: 'Mises Ã  jour de l application',
      appUpdatesDescription: 'VÃ©rifiez les versions signÃ©es publiÃ©es sur GitHub.',
      checkAutomatically: 'VÃ©rifier automatiquement',
      checkAutomaticallyHelp: 'Rechercher des mises Ã  jour au dÃ©marrage de REFX.',
      checking: 'VÃ©rification...',
      checkForUpdates: 'VÃ©rifier les mises Ã  jour',
      downloadInstall: 'TÃ©lÃ©charger et installer',
      latestVersion: 'Vous utilisez dÃ©jÃ  la derniÃ¨re version.',
      updateAvailable: 'Refx {version} est disponible.',
      unableToCheckForUpdates: 'Impossible de vÃ©rifier les mises Ã  jour.',
      preparingUpdate: 'PrÃ©paration de la mise Ã  jour...',
      updateInstallFailed: 'L installation de la mise Ã  jour a Ã©chouÃ©.',
    },
    updateDialog: {
      title: 'Mise Ã  jour disponible',
      descriptionVersion: 'Refx {version} est prÃªt Ã  Ãªtre installÃ©.',
      descriptionFallback: 'Une nouvelle version de Refx est disponible.',
      published: 'PubliÃ© {value}',
      releaseNotes: 'Notes de version',
      noNotes: 'Aucune note de version n a Ã©tÃ© fournie.',
      later: 'Plus tard',
      installing: 'Installation...',
      downloadInstall: 'TÃ©lÃ©charger et installer',
      downloading: 'TÃ©lÃ©chargement de la mise Ã  jour...',
      downloadingKb: 'TÃ©lÃ©chargement de la mise Ã  jour... {size} KB',
      installingStatus: 'Installation de la mise Ã  jour...',
      restarting: 'RedÃ©marrage...',
    },
    home: {
      totalDocuments: 'Total des documents',
      quickActions: 'Actions rapides',
      recentActivity: 'Activité récente',
      noActivity: 'Aucune activité pour le moment',
      noActivityDescription: 'Importez des documents, ajoutez des notes ou créez des surlignages pour alimenter votre activité.',
      openLibraries: 'Ouvrir Bibliothèques',
      libraryCreated: 'Bibliotheque creee',
      documentAdded: 'Document ajoute a la bibliotheque',
      noteCreated: 'Note creee',
      highlightCreated: 'Surlignage cree',
      annotationCreated: 'Annotation creee',
      finishedReading: 'Lecture terminee',
      untitledNote: 'Note sans titre',
      libraryFallback: 'Bibliotheque',
      page: 'Page {page}',
      minutesAgo: 'il y a {count} min',
      hoursAgo: 'il y a {count} h',
      daysAgo: 'il y a {count} j',
      welcomeBackNamed: 'Bon retour, {name}',
      ideasTodayNamed: 'Quelles sont vos idees aujourd hui, {name} ?',
      goodToSeeNamed: 'Heureux de vous revoir, {name}',
      exploringTodayNamed: 'Qu explorez-vous aujourd hui, {name} ?',
      backAtItNamed: 'De retour, {name}',
      attentionTodayNamed: 'Qu est-ce qui merite votre attention aujourd hui, {name} ?',
      moveForwardNamed: 'Que souhaitez-vous faire avancer aujourd hui, {name} ?',
      welcomeBack: 'Bon retour',
      ideasToday: 'Quelles sont vos idees aujourd hui ?',
      goodToSee: 'Heureux de vous revoir',
      exploringToday: 'Qu explorez-vous aujourd hui ?',
      backAtIt: 'De retour',
      attentionToday: 'Qu est-ce qui merite votre attention aujourd hui ?',
      moveForwardToday: 'Que souhaitez-vous faire avancer aujourd hui ?',
    },
    libraries: {
      allLibraries: 'Toutes les bibliothèques',
      search: 'Recherche',
      filters: 'Filtres',
      library: 'Bibliothèque',
      import: 'Importer',
      importing: 'Import...',
      book: 'Livre',
      noDocuments: 'Aucun document trouvé',
      noDocumentsFiltered: 'Essayez d’ajuster les filtres ou la recherche.',
      noDocumentsEmpty: 'Importez des PDF ou enregistrez un livre pour commencer.',
      importPdfs: 'Importer des PDF',
      importingPdfs: 'Import des PDF...',
      registerPhysicalBook: 'Enregistrer un livre papier',
      registerPhysicalBookDescription: 'Ajoutez un livre non PDF à cette bibliothèque pour capturer des notes de lecture par page ou chapitre.',
      title: 'Titre',
      authors: 'Auteurs',
      authorsPlaceholder: 'Noms des auteurs séparés par des virgules',
      year: 'Année',
      isbn: 'ISBN',
      publisher: 'Éditeur',
      description: 'Description',
      descriptionPlaceholder: 'Notes ou résumé facultatifs',
      bookPhoto: 'Photo du livre',
      bookPhotoDescription: 'Facultatif. Ajoutez une photo de couverture depuis cet ordinateur ou scannez un QR code pour l’envoyer depuis votre téléphone.',
      noPhoto: 'Aucune photo sélectionnée',
      uploadFromPc: 'Depuis le PC',
      addFromPhone: 'Depuis le téléphone',
      preparingQr: 'Préparation du QR...',
      removePhoto: 'Supprimer la photo',
      scanWithPhone: 'Scannez avec votre téléphone',
      sameNetwork: 'Gardez l’application desktop ouverte. Le téléphone et l’ordinateur doivent être sur le même réseau local.',
      cancel: 'Annuler',
      registering: 'Enregistrement...',
      registerBook: 'Enregistrer le livre',
      localLibrary: 'Bibliotheque locale',
      documentsCount: '{count} documents',
      sortAdded: 'Date d ajout',
      sortOpened: 'Derniere ouverture',
      sortTitle: 'Titre',
      sortAuthors: 'Auteurs',
      sortYear: 'Annee',
      sortRating: 'Note',
      deduplicate: 'Dedoublonner',
      deduplicateDialogTitle: 'Detecteur de doublons',
      deduplicateDialogDescription: 'Passez en revue les doublons possibles dans {library} par DOI, nom de fichier et taille exacte du fichier.',
      deduplicateDialogDescriptionFallback: 'Passez en revue les doublons possibles par DOI, nom de fichier et taille exacte du fichier.',
      scanningDuplicates: 'Analyse de cette bibliotheque pour trouver des doublons...',
      duplicateScanFailed: 'Impossible de verifier les doublons pour le moment.',
      noDuplicatesFound: 'Aucun groupe en double trouve dans cette bibliotheque.',
      duplicateDocumentsCount: '{count} documents',
      activeFilters: '{count} filtre{suffix}',
      clearFilters: 'Effacer',
      hasComments: 'Avec commentaires',
      hasNotes: 'Avec notes',
      tags: 'Tags',
      noLocalTags: 'Aucun tag local disponible.',
      duplicateDoi: 'Correspondance DOI',
      duplicateFilename: 'Correspondance du nom de fichier',
      duplicateFileSize: 'Correspondance par taille exacte',
      duplicateFileSizeValue: '{size} octets',
      keepDocument: 'Conserver :',
      missingDoi: 'DOI manquant',
      mergeDuplicates: 'Fusionner les doublons',
      mergingDuplicates: 'Fusion...',
      openDocument: 'Ouvrir',
      close: 'Fermer',
      scanning: 'Analyse...',
      rescan: 'Relancer',
      importDocuments: 'Import des documents',
      showingRange: 'Affichage {start}-{end} sur {total}',
    },
    documentTable: {
      favorite: 'Favori',
      title: 'Titre',
      authors: 'Auteurs',
      year: 'Année',
      status: 'Statut',
      metadata: 'Métadonnées',
      comments: 'Commentaires',
      rating: 'Note',
      fetchPossible: 'Recherche possible',
      readingStatus: 'Statut de lecture',
      openComments: 'Ouvrir les commentaires',
      notes: '{count} notes',
      columns: 'Colonnes',
      visibleColumns: 'Colonnes visibles',
      columnOrder: 'Ordre des colonnes',
      generateSuggestions: 'Générer des suggestions',
    },
    notesPage: {
      searchNotes: 'Rechercher des notes',
      allLibraries: 'Toutes les bibliotheques',
      sortTimestamp: 'Trier par date',
      sortPage: 'Trier par page',
      newNote: 'Nouvelle note',
      unlinkedNotes: 'Notes sans lien',
      untitledNote: 'Note sans titre',
      noContent: 'Aucun contenu pour le moment.',
      noNotesForFilters: 'Aucune note trouvee pour les filtres actuels.',
      standaloneNote: 'Note autonome',
      updated: 'Mis a jour {value}',
      openBookNotes: 'Ouvrir les notes du livre',
      openDetails: 'Ouvrir les details',
      openReader: 'Ouvrir dans le lecteur',
      reset: 'Reinitialiser',
      saving: 'Enregistrement...',
      save: 'Enregistrer',
      selectNote: 'Selectionnez une note',
      newNoteTitle: 'Nouvelle note',
    },
    readerIndex: {
      emptyTitle: 'Aucun document a lire',
      emptyDescription: 'Importez des PDF et ouvrez un document pour construire votre file de lecture locale.',
      goLibraries: 'Aller aux bibliotheques',
      title: 'Lecteur',
      subtitle: 'Reprenez la ou vous en etiez ou rouvrez un fichier recent.',
      continueReading: 'Poursuivre la lecture',
      continueLabel: 'Continuer la lecture',
      recentlyOpened: 'Ouverts recemment',
      unknownAuthor: 'Auteur inconnu',
    },
    readerView: {
      loadingPdf: 'Chargement du PDF...',
      openingPdf: 'Ouverture du PDF...',
      renderingPage: 'Rendu de la page {page}...',
      pdfUnavailable: 'PDF indisponible.',
      importPdf: 'Importer un PDF...',
      runningOcr: 'OCR en cours...',
      runOcr: 'Lancer l OCR',
      search: 'Recherche',
      keywordOrPhrase: 'Mot-cle ou expression',
      previous: 'Precedent',
      next: 'Suivant',
      noMatchesKeyword: 'Aucune occurrence trouvee pour ce mot-cle.',
      notes: 'Notes',
      cancel: 'Annuler',
      newNote: 'Nouvelle note',
      moveBalloon: 'Deplacer le repere',
      choosePosition: 'Choisir la position',
      writeNote: 'Ecrivez votre note',
      saving: 'Enregistrement...',
      saveNote: 'Enregistrer la note',
      createNote: 'Creer la note',
      notesOnPage: '{count} note{suffix} sur cette page',
      edit: 'Modifier',
      delete: 'Supprimer',
      noNoteText: 'Aucun texte de note pour le moment.',
      noNotesPage: 'Aucune note sur cette page pour le moment.',
      deleteNoteTitle: 'Supprimer la note ?',
      deleteNoteDescription: 'Cela supprimera definitivement {label} de ce document.',
      deleteNoteDescriptionFallback: 'Cela supprimera definitivement cette note du document.',
      clickOrDrawNote: 'Cliquez ou dessinez une zone pour placer une note',
      drawHighlight: 'Dessinez une zone a surligner',
      exactRegion: 'Zone exacte',
      pageFallback: 'Repli par page',
      occurrence: 'Occurrence {index}',
      approxPage: 'Page approx',
    },
    metadataPage: {
      workspace: 'Espace metadonnees',
      title: 'Metadonnees',
      subtitle: 'Revoyez les correspondances DOI et corrigez les documents incomplets par bibliotheque.',
      back: 'Retour',
      library: 'Bibliotheque',
      selectLibrary: 'Choisir une bibliotheque',
      fetchPossible: 'Recherche possible',
      missing: 'Manquant',
      noLibrary: 'Aucune bibliotheque selectionnee',
      noLibraryDescription: 'Choisissez une bibliotheque pour commencer la revision des metadonnees.',
      noFetchQueue: 'Aucune file DOI',
      noMissingQueue: 'Aucune file manquante',
      openDetails: 'Ouvrir les details complets',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      doiReview: 'Revue DOI',
      doiReviewDescription: 'Revoyez les candidats bases sur le DOI et choisissez le meilleur resultat.',
      manualReview: 'Revue manuelle',
      manualReviewDescription: 'Utilisez les fleches pour parcourir les documents qui ont encore besoin d une correction manuelle.',
      refresh: 'Actualiser',
      searching: 'Recherche...',
      searchAcrossProviders: 'Recherche par DOI dans Semantic Scholar, OpenAlex et Crossref...',
      noCandidates: 'Aucun candidat de metadonnees trouve pour ce DOI.',
      fillMissing: 'Completer les champs manquants',
      applyCandidate: 'Appliquer le candidat',
      manualQueueHelp: 'Cette file est destinee au nettoyage manuel. Utilisez les champs a gauche, enregistrez puis passez au document suivant.',
    },
    searchPage: {
      title: 'Recherche',
      subtitle: 'Recherche indexee dans toute la bibliotheque avec MiniSearch local.',
      subtitleCompact: 'Recherchez dans toute votre bibliotheque.',
      advancedFilters: 'Filtres avances',
      advancedFiltersDescription: 'Construisez des requetes groupees avec la logique AND/OR puis lancez-les sur la bibliotheque choisie.',
      advancedFiltersCompact: 'Mode de recherche, filtres et regles de correspondance.',
      queryMode: 'Mode de requete',
      queryModeHelp: 'Le mode simple est ideal pour les recherches rapides. Le mode complexe permet de creer des groupes de phrases.',
      simple: 'Simple',
      complex: 'Complexe',
      keywordQuery: 'Requete par mots-cles',
      keywordQueryHelp: 'La recherche simple accepte les expressions entre guillemets. En mode complexe, chaque mot-cle est traite comme une phrase.',
      addGroup: 'Ajouter un groupe',
      quickSearch: 'Recherche rapide',
      quickSearchPlaceholder: 'Rechercher dans l index local plein texte',
      search: 'Rechercher',
      simpleHelp: 'Appuyez sur Entree ou Rechercher. Utilisez des guillemets pour les expressions exactes.',
      betweenGroups: 'Entre les groupes',
      everyGroup: 'Un document doit satisfaire tous les groupes.',
      anyGroup: 'Un document peut satisfaire n importe quel groupe.',
      group: 'Groupe {index}',
      addKeywordPlaceholder: 'Ajouter un mot-cle a ce groupe',
      add: 'Ajouter',
      addKeywordsHelpAnd: 'Ajoutez un ou plusieurs mots-cles. Chaque mot-cle est traite comme une expression, et le groupe ne correspond que si toutes sont trouvees.',
      addKeywordsHelpOr: 'Ajoutez un ou plusieurs mots-cles. Chaque mot-cle est traite comme une expression, et le groupe correspond si l une d elles est trouvee.',
      flexibility: 'Souplesse',
      strict: 'Stricte',
      balanced: 'Equilibree',
      flexible: 'Souple',
      veryFlexible: 'Tres souple',
      flexibilityHelp: 'Une plus grande souplesse autorise les variantes proches, fautes de frappe, mots coupes et correspondances proches.',
      library: 'Bibliotheque',
      readingStage: 'Statut de lecture',
      anyStage: 'N importe quel statut',
      metadataQuality: 'Qualite des metadonnees',
      anyStatus: 'N importe quel statut',
      favoritesOnly: 'Favoris uniquement',
      filterFavorites: 'Filtrer les favoris',
      persistentSearch: 'Recherche indexee persistante',
      searchingDocs: 'Recherche de {processed}/{total} documents pour {query}',
      resultsFor: '{count} resultat{suffix} pour {query}',
      searchingBadge: 'Recherche',
      startTitle: 'Commencez une recherche',
      startDescriptionSimple: 'Tapez dans le champ de recherche pour interroger votre bibliotheque locale indexee.',
      startDescriptionComplex: 'Ajoutez un ou plusieurs groupes puis appuyez sur Rechercher pour parcourir toute la bibliotheque.',
      loadingFallback: 'Interrogation de l index local MiniSearch et resolution des extraits a partir du texte stocke.',
      noMatchesTitle: 'Aucun document correspondant',
      noMatchesDescription: 'Essayez d augmenter la souplesse ou d elargir les filtres.',
      unknownAuthor: 'Auteur inconnu',
      page: 'Page {page}',
      openReader: 'Ouvrir dans le lecteur',
      openDetails: 'Ouvrir les details',
      exactRegion: 'Region exacte',
      pageFallback: 'Repli par page',
      occurrence: 'Occurrence {index}',
      approxPage: 'Page approx',
      noMatchesForKeyword: 'Aucune occurrence trouvee pour ce mot-cle.',
      preparingIndex: 'Preparation de l index de recherche local...',
      resultsReady: '{count} resultat{suffix} pret',
    },
    mapsPage: {
      title: 'Cartes',
      subtitle: 'Explorez les relations, organisez les vues enregistrees et creez des liens directement sur le canevas.',
      workspace: 'Espace de travail',
      workingMap: 'Carte en cours',
      workingMapDescription: 'Choisissez une vue enregistree ou continuez a organiser la carte actuelle.',
      mapView: 'Vue de la carte',
      canvasEditor: 'Editeur du canevas',
      addReferencedDocument: 'Ajouter un document reference',
      addCitingDocument: 'Ajouter un document citant',
      addDocument: 'Ajouter un document',
      addDocumentHelp: 'Recherchez dans la bibliotheque actuelle et ajoutez un autre document a cette carte.',
      addDocumentLinkHelp: 'Recherchez dans la bibliotheque, ajoutez le document au canevas et reliez-le dans le meme flux.',
      findReferencedDocument: 'Trouver le document reference',
      findCitingDocument: 'Trouver le document citant',
      addDocumentToMap: 'Ajouter un document a la carte',
      myWork: 'Mon travail',
      noDocumentsControls: 'Aucun document ne correspond aux controles actuels.',
      noLinksControls: 'Aucun lien ne correspond aux controles actuels.',
      saveGraphView: 'Enregistrer la vue du graphe',
      saveGraphViewDescription: 'Enregistrez la carte actuelle comme espace reutilisable avec ses filtres, son sous-ensemble et sa disposition.',
      editGraphView: 'Modifier la vue du graphe',
      editGraphViewDescription: 'Renommez cet espace ou mettez sa description a jour sans changer les relations des documents.',
      cancel: 'Annuler',
      saveView: 'Enregistrer la vue',
      saveChanges: 'Enregistrer les modifications',
      saveAsNewView: 'Enregistrer comme nouvelle vue',
      saveCurrentView: 'Enregistrer les modifications',
      saveCurrentViewHelp: 'Mettre a jour la vue enregistree actuellement selectionnee',
      saveNewViewHelp: 'Enregistrer cette disposition et ces filtres comme vue reutilisable',
      rebuildLayout: 'Reconstruire la disposition',
      rebuildLayoutHelp: 'Repartir les noeuds visibles pour ameliorer la disposition',
      showControls: 'Afficher les controles',
      hideControls: 'Masquer les controles',
      renameView: 'Renommer la vue',
      duplicateView: 'Dupliquer',
      resetLayout: 'Reinitialiser la disposition',
      resetLayoutHelp: 'Reinitialiser la position des noeuds dans cette vue enregistree',
      delete: 'Supprimer',
      addMyWork: 'Ajouter "mon travail"',
      addMyWorkDescription: 'Creez un noeud pour votre propre travail. Il est enregistre dans la bibliotheque et peut faire reference a d autres documents.',
      addToMap: 'Ajouter a la carte',
      workName: 'Nom du travail',
      workNamePlaceholder: 'Mon brouillon d article',
      name: 'Nom',
      workspaceNote: 'Note de l espace',
      workspaceNotePlaceholder: 'Pourquoi cette carte existe, ce que signifie ce sous-ensemble ou ce qu il faut revoir ensuite.',
      searchDocumentsPlaceholder: 'Rechercher des documents...',
      searchAndLinkPlaceholder: 'Rechercher et ajouter un document a relier...',
      noMatchingDocument: 'Aucun document correspondant trouve.',
      selectReferenceTarget: 'Selectionnez le document auquel celui-ci fait reference, ou recherchez-le pour l ajouter',
      selectCitationTarget: 'Selectionnez le document qui fait reference a celui-ci, ou recherchez-le pour l ajouter',
      deleteNode: 'Supprimer le noeud',
      deleteAllLinks: 'Supprimer tous les liens',
      removeLinkMenu: 'Supprimer le lien',
      invertLinkMenu: 'Inverser le lien',
      relationDetails: 'Details de la relation',
      relationDetailsDescription: 'Selectionnez un document pour l inspecter ou cliquez sur une connexion pour revoir ou supprimer la relation.',
      relation: 'Relation',
      relationDescription: 'Examinez ce lien enregistre entre deux documents.',
      closeDetails: 'Fermer les details',
      citingDocument: 'Document citant',
      referencedDocument: 'Document reference',
      makesReferenceTo: 'Fait reference a',
      isReferencedBy: 'Est reference par',
      reverseLinkDirection: 'Inverser la direction du lien',
      reverseLinkDirectionHelp: 'Echanger le document qui pointe vers l autre',
      removeLink: 'Supprimer le lien',
      removeLinkHelp: 'Supprimer cette connexion de la carte',
      physicalBook: 'Livre physique',
      myWorkType: 'Mon travail',
      pdfDocument: 'Document PDF',
      author: 'Auteur',
      abstract: 'Resume',
      collapse: 'Reduire',
      expand: 'Developper',
      none: 'aucun',
      addOrConnect: 'Ajouter ou connecter des documents lies',
      addReference: 'Ajouter une reference',
      addReferenceHelp: 'Relier ce document a celui auquel il fait reference',
      addCitation: 'Ajouter une citation',
      addCitationHelp: 'Relier un document qui cite celui-ci',
      findDocument: 'Trouver un document',
      findDocumentHelp: 'Recherchez dans cette carte et sautez vers un noeud correspondant.',
      searchTitlesInMap: 'Rechercher des titres dans cette carte',
      jumpToMatchingDocument: 'Aller au document correspondant',
      filterLayout: 'Filtres et disposition',
      filterLayoutHelp: 'Afficher les filtres du graphe, les options de disposition et les outils rapides',
      expandControls: 'Developper',
      collapseControls: 'Reduire',
      appearance: 'Apparence',
      appearanceDescription: 'Controlez l apparence des documents dans le graphe.',
      nodeColors: 'Couleurs des noeuds',
      libraryColors: 'Bibliotheque',
      yearColors: 'Annee',
      density: 'Densite',
      status: 'Statut',
      component: 'Composant',
      nodeSize: 'Taille du noeud',
      uniform: 'Uniforme',
      inboundCitations: 'Citations entrantes',
      totalDegree: 'Degre total',
      focus: 'Focus',
      focusDescription: 'Limitez la vue autour du document selectionne si besoin.',
      focusType: 'Type de focus',
      fullGraph: 'Graphe complet',
      oneHopNeighbors: 'Voisins a 1 saut',
      twoHopNeighbors: 'Voisins a 2 sauts',
      hideIsolated: 'Masquer les documents isoles',
      hideIsolatedDescription: 'Retirer les documents sans liens visibles.',
      years: 'Annees',
      yearsDescription: 'Restreignez les documents visibles par annee de publication.',
      from: 'De',
      to: 'A',
      any: 'Toutes',
    },
    metadataFields: {
      title: 'Titre',
      authors: 'Auteurs',
      year: 'Annee',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Editeur',
      citationKey: 'Cle de citation',
      abstract: 'Resume',
      untitledDocument: 'Document sans titre',
      queuePosition: '{current} sur {total}',
      allCompleteDescription: 'Tous les documents avec DOI dans {library} semblent deja complets.',
      noMissingDescription: 'Aucun document sans option de recherche DOI n attend dans {library}.',
    },
    common: {
      unread: 'Non lu',
      reading: 'En lecture',
      finished: 'Terminé',
      missing: 'Manquant',
      partial: 'Partiel',
      complete: 'Complet',
      ocrPending: 'OCR en attente',
      processing: 'Traitement',
      ocrComplete: 'OCR terminé',
      ocrFailed: 'OCR échoué',
      nativeText: 'Texte natif',
      new: 'NOUVEAU',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },
} as const satisfies Record<AppLocale, Record<string, unknown>>

const LocaleContext = createContext<LocaleContextValue>({
  locale: DEFAULT_LOCALE,
  setLocale: () => undefined,
  t: (key) => key,
})

function getNestedValue(source: Record<string, unknown>, key: string): string | undefined {
  return key.split('.').reduce<unknown>((current, part) => {
    if (current && typeof current === 'object' && part in current) {
      return (current as Record<string, unknown>)[part]
    }
    return undefined
  }, source) as string | undefined
}

function interpolate(template: string, params?: TranslationParams) {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`))
}

export function translate(locale: AppLocale, key: string, params?: TranslationParams) {
  const localized = getNestedValue(translations[locale], key)
  const fallback = getNestedValue(translations.en, key)
  return interpolate(localized ?? fallback ?? key, params)
}

export function LocaleProvider({ initialLocale, children }: { initialLocale: AppLocale; children: React.ReactNode }) {
  const [locale, setLocale] = useState<AppLocale>(initialLocale)

  useEffect(() => {
    setLocale(initialLocale)
  }, [initialLocale])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const listener = (event: Event) => {
      const detail = (event as CustomEvent<StoredAppSettings>).detail
      if (detail?.locale) setLocale(detail.locale)
    }
    window.addEventListener('refx-settings-changed', listener)
    return () => window.removeEventListener('refx-settings-changed', listener)
  }, [])

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale
    }
  }, [locale])

  const value = useMemo<LocaleContextValue>(
    () => ({
      locale,
      setLocale,
      t: (key, params) => translate(locale, key, params),
    }),
    [locale],
  )

  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>
}

export function useLocale() {
  return useContext(LocaleContext)
}

export function useT() {
  return useContext(LocaleContext).t
}

export const APP_LOCALES: AppLocale[] = ['en', 'pt-BR', 'fr']
