'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { StoredAppSettings } from '@/lib/app-settings'

export type AppLocale = 'en' | 'pt-BR' | 'fr'

type TranslationParams = Record<string, string | number>

type LocaleContextValue = {
  locale: AppLocale
  setLocale: (locale: AppLocale) => void
  t: (key: string, params?: TranslationParams) => string
}

const DEFAULT_LOCALE: AppLocale = 'en'

const translations = {
  en: {
    nav: {
      home: 'Home',
      search: 'Search',
      libraries: 'Libraries',
      reader: 'Reader',
      references: 'My References',
      notes: 'Notes',
      maps: 'Maps',
      metadata: 'Metadata',
      reports: 'Reports',
      libraryGroup: 'Libraries',
      researchWorkspace: 'Research workspace',
      expandSidebar: 'Expand sidebar',
      collapseSidebar: 'Collapse sidebar',
    },
    topBar: {
      searchPlaceholder: 'Search',
      command: 'Commands',
      toggleTheme: 'Toggle theme',
      openSettings: 'Open settings',
    },
    commandBar: {
      placeholder: 'Type a command or search...',
      empty: 'No local results found.',
      navigation: 'Navigation',
      actions: 'Actions',
      libraries: 'Libraries',
      recentDocuments: 'Recent documents',
      toggleTheme: 'Toggle theme',
      openSettings: 'Open settings',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Drop PDFs to import',
      dropDescription: 'REFX will open Libraries and continue the import there.',
    },
    appProvider: {
      loadingWorkspace: 'Loading workspace...',
      welcomeTitle: 'Welcome to REFX',
      welcomeDescription: 'Set your name to personalize the dashboard.',
      yourName: 'Your name',
      namePlaceholder: 'Enter your name',
      dontAskAgain: "Don't ask again",
      continueWithoutName: 'Continue without a name',
      continue: 'Continue',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Preferences for this device.',
      adjustLocalBehavior: 'Adjust local behavior.',
      general: 'General',
      display: 'Appearance',
      processing: 'Processing',
      data: 'Data',
      about: 'About',
      profileTitle: 'Profile',
      profileDescription: 'Name used across your workspace.',
      yourName: 'Your name',
      yourNamePlaceholder: 'Enter your name',
      yourNameHelp: 'Leave blank for an impersonal greeting. You can change this later.',
      language: 'Language',
      appearanceTitle: 'Appearance',
      appearanceDescription: 'Appearance for this device.',
      theme: 'Theme',
      fontSize: 'Font size',
      appUpdates: 'App updates',
      appUpdatesDescription: 'Check for signed releases published on GitHub.',
      checkAutomatically: 'Check automatically',
      checkAutomaticallyHelp: 'Look for updates when REFX starts.',
      checking: 'Checking...',
      checkForUpdates: 'Check for updates',
      downloadInstall: 'Download & install',
      latestVersion: 'You are on the latest version.',
      updateAvailable: 'Refx {version} is available.',
      unableToCheckForUpdates: 'Unable to check for updates.',
      preparingUpdate: 'Preparing update...',
      updateInstallFailed: 'Update install failed.',
    },
    updateDialog: {
      title: 'Update available',
      descriptionVersion: 'Refx {version} is ready to install.',
      descriptionFallback: 'A new version of Refx is available.',
      published: 'Published {value}',
      releaseNotes: 'Release notes',
      noNotes: 'No release notes provided.',
      later: 'Later',
      installing: 'Installing...',
      downloadInstall: 'Download & install',
      downloading: 'Downloading update...',
      downloadingKb: 'Downloading update... {size} KB',
      downloadingProgress: 'Downloading update... {downloaded} / {total} KB',
      installingStatus: 'Installing update...',
      restarting: 'Restarting...',
    },
    home: {
      totalDocuments: 'Total documents',
      quickActions: 'My libraries',
      recentActivity: 'Recent activity',
      noActivity: 'No activity yet',
      noActivityDescription: 'Import documents, add notes, or create highlights to build your activity feed.',
      openLibraries: 'Open Libraries',
      libraryCreated: 'Library created',
      documentAdded: 'Document added to library',
      noteCreated: 'Note created',
      highlightCreated: 'Highlight created',
      annotationCreated: 'Annotation created',
      finishedReading: 'Finished reading',
      untitledNote: 'Untitled note',
      libraryFallback: 'Library',
      bundledActivitySummary: 'Many actions, click to see more',
      page: 'Page {page}',
      minutesAgo: '{count}m ago',
      hoursAgo: '{count}h ago',
      daysAgo: '{count}d ago',
      welcomeBackNamed: 'Welcome back, {name}',
      ideasTodayNamed: 'What are your ideas today, {name}?',
      goodToSeeNamed: 'Good to see you again, {name}',
      exploringTodayNamed: 'What are you exploring today, {name}?',
      backAtItNamed: 'Back at it, {name}',
      attentionTodayNamed: 'What deserves your attention today, {name}?',
      moveForwardNamed: 'What do you want to move forward today, {name}?',
      welcomeBack: 'Welcome back',
      ideasToday: 'What are your ideas today?',
      goodToSee: 'Good to see you again',
      exploringToday: 'What are you exploring today?',
      backAtIt: 'Back at it',
      attentionToday: 'What deserves your attention today?',
      moveForwardToday: 'What do you want to move forward today?',
    },
    documentDetailPage: {
      information: 'Document Information',
      tagsAndClassification: 'Tags and Classification ({count})',
      suggestedTags: 'Suggested Tags ({count})',
      semanticClassification: 'Semantic Classification',
      classifyLocal: 'Classify with local heuristic',
      reclassifyLocal: 'Reclassify with local heuristic',
      classifyAi: 'Classify with AI from the same first-page pass as AI tags',
      classificationDisabled: 'Semantic classification is disabled in Settings.',
      classificationNeedsText: 'This document needs extracted or OCR text before it can be classified.',
      aiClassificationFinished: 'AI classification finished.',
      aiClassificationFailed: 'AI classification failed.',
      aiClassificationNotSaved: 'AI classification was not saved.',
      noClassificationSaved: 'No semantic classification saved for this document.',
      referencesAndCitations: 'References & Citations ({outgoing}/{incoming})',
      findReferences: 'Find references',
    },
    libraries: {
      allLibraries: 'All libraries',
      search: 'Search',
      filters: 'Filters',
      library: 'Library',
      import: 'Import',
      importing: 'Importing...',
      book: 'Book',
      noDocuments: 'No documents found',
      noDocumentsFiltered: 'Try adjusting your filters or search.',
      noDocumentsEmpty: 'Import PDFs or register a book to get started.',
      importPdfs: 'Import PDFs',
      importingPdfs: 'Importing PDFs...',
      registerPhysicalBook: 'Register physical book',
      registerPhysicalBookDescription: 'Add a non-PDF book to this library to capture reading notes by page or chapter.',
      title: 'Title',
      authors: 'Authors',
      authorsPlaceholder: 'Comma-separated author names',
      year: 'Year',
      isbn: 'ISBN',
      publisher: 'Publisher',
      description: 'Description',
      descriptionPlaceholder: 'Optional notes or summary',
      bookPhoto: 'Book photo',
      bookPhotoDescription: 'Optional. Add a cover photo from this computer or scan a QR code to upload from your phone.',
      noPhoto: 'No photo selected yet',
      uploadFromPc: 'Upload from PC',
      addFromPhone: 'Add from phone',
      preparingQr: 'Preparing QR...',
      removePhoto: 'Remove photo',
      scanWithPhone: 'Scan with your phone',
      sameNetwork: 'Keep the desktop app open. Your phone and computer must be on the same local network.',
      cancel: 'Cancel',
      registering: 'Registering...',
      registerBook: 'Register book',
      localLibrary: 'Local library',
      documentsCount: '{count} documents',
      sortAdded: 'Date added',
      sortOpened: 'Last opened',
      sortTitle: 'Title',
      sortAuthors: 'Authors',
      sortYear: 'Year',
      sortRating: 'Rating',
      deduplicate: 'Deduplicate',
      deduplicateDialogTitle: 'Duplicate checker',
      deduplicateDialogDescription: 'Review possible duplicates in {library} by DOI, filename, and exact file size.',
      deduplicateDialogDescriptionFallback: 'Review possible duplicates by DOI, filename, and exact file size.',
      scanningDuplicates: 'Scanning this library for duplicates...',
      duplicateScanFailed: 'Unable to scan for duplicates right now.',
      noDuplicatesFound: 'No duplicate groups found in this library.',
      duplicateDocumentsCount: '{count} documents',
      activeFilters: '{count} filter{suffix}',
      clearFilters: 'Clear',
      hasComments: 'Has comments',
      hasNotes: 'Has notes',
      tags: 'Tags',
      noLocalTags: 'No local tags available.',
      duplicateDoi: 'DOI match',
      duplicateFilename: 'Filename match',
      duplicateFileSize: 'Exact file size match',
      duplicateFileSizeValue: '{size} bytes',
      keepDocument: 'Keep:',
      missingDoi: 'Missing DOI',
      mergeDuplicates: 'Merge duplicates',
      mergingDuplicates: 'Merging...',
      openDocument: 'Open',
      close: 'Close',
      scanning: 'Scanning...',
      rescan: 'Rescan',
      importDocuments: 'Importing documents',
      showingRange: 'Showing {start}–{end} of {total}',
    },
    documentTable: {
      favorite: 'Favorite',
      title: 'Title',
      authors: 'Authors',
      tags: 'Tags',
      year: 'Year',
      status: 'Status',
      metadata: 'Metadata',
      comments: 'Comments',
      rating: 'Rating',
      fetchPossible: 'Fetch possible',
      readingStatus: 'Reading status',
      openComments: 'Open comments',
      notes: '{count} notes',
      columns: 'Columns',
      visibleColumns: 'Visible columns',
      columnOrder: 'Column order',
      generateSuggestions: 'Generate suggestions',
    },
    notesPage: {
      searchNotes: 'Search notes',
      allLibraries: 'All libraries',
      sortTimestamp: 'Sort by date',
      sortPage: 'Sort by page',
      newNote: 'New note',
      unlinkedNotes: 'Unlinked notes',
      untitledNote: 'Untitled note',
      noContent: 'No content yet.',
      noNotesForFilters: 'No notes match the current filters.',
      standaloneNote: 'Standalone note',
      seeInDocument: 'See in document',
      updated: 'Updated {value}',
      openBookNotes: 'Open book notes',
      openDetails: 'Open details',
      openReader: 'Open in reader',
      reset: 'Reset',
      saving: 'Saving...',
      save: 'Save',
      selectNote: 'Select a note',
      newNoteTitle: 'New note',
    },
    readerIndex: {
      emptyTitle: 'No documents to read',
      emptyDescription: 'Import PDFs and open a document to build your local reading queue.',
      goLibraries: 'Go to Libraries',
      title: 'Reader',
      subtitle: 'Continue where you left off or jump back into recent files.',
      continueReading: 'Continue reading',
      continueLabel: 'Continue reading',
      recentlyOpened: 'Recently opened',
      unknownAuthor: 'Unknown author',
    },
    readerView: {
      loadingPdf: 'Loading PDF...',
      openingPdf: 'Opening PDF...',
      renderingPage: 'Rendering page {page}...',
      pdfUnavailable: 'PDF unavailable.',
      importPdf: 'Import PDF...',
      runningOcr: 'Running OCR...',
      runOcr: 'Run OCR',
      search: 'Search',
      keywordOrPhrase: 'Keyword or phrase',
      previous: 'Previous',
      next: 'Next',
      noMatchesKeyword: 'No matches found for this keyword.',
      notes: 'Notes',
      cancel: 'Cancel',
      newNote: 'New note',
      moveBalloon: 'Move marker',
      choosePosition: 'Choose position',
      writeNote: 'Write your note',
      saving: 'Saving...',
      saveNote: 'Save note',
      createNote: 'Create note',
      notesOnPage: '{count} note{suffix} on this page',
      edit: 'Edit',
      delete: 'Delete',
      noNoteText: 'No note text yet.',
      noNotesPage: 'No notes on this page yet.',
      deleteNoteTitle: 'Delete note?',
      deleteNoteDescription: 'This will permanently remove {label} from this document.',
      deleteNoteDescriptionFallback: 'This will permanently remove this note from the document.',
      clickOrDrawNote: 'Click or draw a box to place a note',
      drawHighlight: 'Draw a box to highlight',
      exactRegion: 'Exact region',
      pageFallback: 'Page-level fallback',
      occurrence: 'Occurrence {index}',
      approxPage: 'Approx. page',
    },
    metadataPage: {
      workspace: 'Metadata workspace',
      title: 'Metadata',
      subtitle: 'Review DOI matches and fix incomplete documents by library.',
      back: 'Back',
      library: 'Library',
      selectLibrary: 'Select a library',
      fetchPossible: 'Fetch possible',
      missing: 'Missing',
      noLibrary: 'No library selected',
      noLibraryDescription: 'Choose a library to start reviewing metadata.',
      noFetchQueue: 'No documents with a DOI fetch available',
      noMissingQueue: 'No documents with missing metadata',
      openDetails: 'Open details',
      save: 'Save',
      saving: 'Saving...',
      doiReview: 'DOI review',
      doiReviewDescription: 'Review DOI-based candidates and pick the best match.',
      manualReview: 'Manual review',
      manualReviewDescription: 'Step through documents that still need manual metadata cleanup.',
      refresh: 'Refresh',
      searching: 'Searching...',
      searchAcrossProviders: 'Searching by DOI across Semantic Scholar, OpenAlex, and Crossref...',
      noCandidates: 'No metadata candidates found for this DOI.',
      fillMissing: 'Fill missing fields',
      applyCandidate: 'Apply candidate',
      manualQueueHelp: 'Focused on manual cleanup. Edit the fields on the left, save, then move to the next document.',
    },
    searchPage: {
      title: 'Search',
      subtitle: 'Full-library indexed search powered by local MiniSearch.',
      subtitleCompact: 'Search across your library.',
      advancedFilters: 'Advanced filters',
      advancedFiltersDescription: 'Build grouped queries with AND/OR logic, then run them across the selected library.',
      advancedFiltersCompact: 'Search mode, filters, and match rules.',
      queryMode: 'Query mode',
      queryModeHelp: 'Simple is best for quick searches. Complex lets you build grouped phrase queries.',
      simple: 'Simple',
      complex: 'Complex',
      keywordQuery: 'Keyword query',
      keywordQueryHelp: 'Simple search supports quoted phrases. In complex mode, each keyword is treated as one phrase.',
      addGroup: 'Add group',
      quickSearch: 'Quick search',
      quickSearchPlaceholder: 'Search',
      search: 'Search',
      simpleHelp: 'Press Enter or Search. Use quotes for exact phrases.',
      betweenGroups: 'Between groups',
      everyGroup: 'A document must satisfy every group.',
      anyGroup: 'A document can satisfy any one group.',
      group: 'Group {index}',
      addKeywordPlaceholder: 'Add a keyword to this group',
      add: 'Add',
      addKeywordsHelpAnd: 'Each keyword is treated as a phrase. This group matches only when all keywords are found.',
      addKeywordsHelpOr: 'Each keyword is treated as a phrase. This group matches when any keyword is found.',
      flexibility: 'Flexibility',
      strict: 'Strict',
      balanced: 'Balanced',
      flexible: 'Flexible',
      veryFlexible: 'Very flexible',
      flexibilityHelp: 'Higher flexibility allows near-variants, typos, line-break splits, and approximate matches.',
      library: 'Library',
      selectAll: 'Select all',
      clearSelection: 'Clear',
      selectedCount: '{count} selected',
      allShort: 'All',
      readingStage: 'Reading stage',
      anyStage: 'Any stage',
      metadataQuality: 'Metadata quality',
      anyStatus: 'Any status',
      favoritesOnly: 'Showing favorites only',
      filterFavorites: 'Favorites only',
      persistentSearch: 'Persistent indexed search',
      searchingDocs: 'Searching {processed}/{total} documents for {query}',
      resultsFor: '{count} result{suffix} for {query}',
      searchingBadge: 'Searching',
      startTitle: 'Start a search',
      startDescriptionSimple: 'Type in the search box to query your indexed library.',
      startDescriptionComplex: 'Add one or more groups and press Search to scan your full library.',
      loadingFallback: 'Querying the local MiniSearch index and resolving snippets from stored text.',
      noMatchesTitle: 'No matching documents',
      noMatchesDescription: 'Try increasing flexibility or broadening the filters.',
      unknownAuthor: 'Unknown author',
      page: 'Page {page}',
      openReader: 'Open in reader',
      openDetails: 'Open details',
      exactRegion: 'Exact region',
      pageFallback: 'Page-level fallback',
      occurrence: 'Occurrence {index}',
      approxPage: 'Approx. page',
      noMatchesForKeyword: 'No matches found for this keyword.',
      preparingIndex: 'Preparing local search index...',
      resultsReady: '{count} result{suffix} ready',
    },
    referencesPage: {
      title: 'My References',
      subtitle: 'Build reusable bibliographies for your work, mix matched documents and freeform references, and copy them in your preferred style.',
      citationStyle: 'Citation style',
      addWork: 'Add work',
      works: 'Works',
      worksHelp: 'Choose a My work item or create a new one.',
      selectWork: 'Select a work',
      referencesCount: '{count} reference{suffix}',
      noWorkSelected: 'No work selected',
      selectWorkToManage: 'Select a work to manage its bibliography.',
      createFirstWork: 'Create your first work to start collecting references.',
      bibliography: 'Bibliography',
      bibliographyHelp: 'Drag to reorder. Copy any entry in {style} format.',
      addReference: 'Add reference',
      addReferenceDescription: 'Match one of your documents when possible, or save a freeform reference that only exists in this bibliography.',
      recheckMatches: 'Recheck matches',
      loadingReferences: 'Loading references...',
      noReferencesYet: 'No references yet',
      noReferencesYetDescription: 'Add references to build the bibliography for this work.',
      existsInLibraries: 'Exists in libraries',
      copyReference: 'Copy reference',
      removeReference: 'Remove reference',
      addWorkDescription: 'Create a My work item that can hold an ordered bibliography.',
      workName: 'Work name',
      workNamePlaceholder: 'My article draft',
      createWork: 'Create work',
      deleteWork: 'Delete work',
      deleteWorkDescription: 'This will permanently remove "{title}" and its linked bibliography entries from this work.',
      deleteWorkDescriptionFallback: 'This will permanently remove this work and its linked bibliography entries.',
      cancel: 'Cancel',
      type: 'Type',
      referenceType: 'Reference type',
      referenceTypeArticle: 'Article',
      referenceTypeBook: 'Book',
      referenceTypeConference: 'Conference',
      referenceTypeThesis: 'Thesis',
      referenceTypeReport: 'Report',
      referenceTypeOnline: 'Online',
      referenceTypeMisc: 'Misc',
      referenceTitlePlaceholder: 'Reference title',
      authorsPlaceholder: 'Author One; Author Two',
      publisherSource: 'Publisher / source',
      publisherPlaceholder: 'Publisher',
      journal: 'Journal',
      journalPlaceholder: 'Journal name',
      booktitleCollection: 'Booktitle / collection',
      booktitlePlaceholder: 'Book or proceedings',
      url: 'URL',
      urlPlaceholder: 'https://example.org',
      abstractNote: 'Abstract / note',
      abstractPlaceholder: 'Optional summary or note',
      matchingSuggestions: 'Matching suggestions',
      matchingSuggestionsDescription: 'Existing documents are suggested by DOI first, then title, author, and year.',
      matchingSuggestionsEmpty: 'Type a title, DOI, or author to see matching documents from your library.',
      matchPercent: 'Match {percent}%',
      alreadyInWork: 'Already in this work',
      referenceWillBeLinked: 'This reference will be linked to an existing document if the match stays valid.',
      freeformReferenceHelp: 'You can still save a freeform unmatched reference.',
      removeReferenceConfirm: 'Remove this reference from the current work?',
      removeReferenceConfirmNamed: 'Remove "{title}" from this work?',
      remove: 'Remove',
      couldNotLoadReferences: 'Could not load references.',
      couldNotLoadWorkReferences: 'Could not load work references.',
      selectWorkBeforeAddingReferences: 'Select a work before adding references.',
      workNameRequired: 'A work name is required.',
      createLibraryBeforeAddingWork: 'Create a library before adding a work.',
      createdWork: 'Created "{title}".',
      couldNotCreateWork: 'Could not create the work.',
      deletedWork: 'Deleted "{title}".',
      couldNotDeleteWork: 'Could not delete the work.',
      addedDocumentToWork: 'Added "{title}" to this work.',
      couldNotAddReference: 'Could not add the reference.',
      referenceTitleRequired: 'Reference title is required.',
      referenceAdded: 'Reference added.',
      couldNotCopyReference: 'Could not copy the reference.',
      referenceRemovedFromWork: 'Reference removed from this work.',
      couldNotRemoveReference: 'Could not remove the reference.',
      referenceMatchesRefreshed: 'Reference matches refreshed.',
      couldNotRefreshMatches: 'Could not refresh matches.',
      couldNotReorderReferences: 'Could not reorder references.',
    },
    mapsPage: {
      title: 'Maps',
      subtitle: 'Explore how documents interconnect with references and citations.',
      workspace: 'Workspace',
      workingMap: 'Select map',
      workingMapDescription: 'Choose one of the saved maps in this library.',
      mapView: 'Map view',
      canvasEditor: 'Canvas editor',
      addReferencedDocument: 'Add referenced document',
      addCitingDocument: 'Add citing document',
      addDocument: 'Add document',
      addDocumentHelp: 'Search the current library and bring another document into this map.',
      addDocumentLinkHelp: 'Search the library, add the document to the canvas, and connect it in one step.',
      findReferencedDocument: 'Find referenced document',
      findCitingDocument: 'Find citing document',
      addDocumentToMap: 'Add document to map',
      myWork: 'My work',
      noDocumentsControls: 'No documents match the current controls.',
      noLinksControls: 'No links match the current controls.',
      saveGraphView: 'Save map view',
      saveGraphViewDescription: 'Save the current map as a reusable workspace with its filters, subset, and layout.',
      editGraphView: 'Edit map view',
      editGraphViewDescription: 'Rename this workspace or update its description without changing document relations.',
      cancel: 'Cancel',
      saveView: 'Save view',
      saveChanges: 'Save changes',
      saveAsNewView: 'Save as new view',
      saveCurrentView: 'Save changes',
      saveCurrentViewHelp: 'Update the currently selected saved view',
      saveNewViewHelp: 'Save this layout and filters as a new reusable view',
      newMap: 'New map',
      rebuildLayout: 'Rebuild layout',
      rebuildLayoutHelp: 'Re-space the visible nodes to improve the layout',
      deleteMap: 'Delete map',
      showControls: 'Show controls',
      hideControls: 'Hide controls',
      renameView: 'Rename view',
      duplicateView: 'Duplicate',
      resetLayout: 'Reset layout',
      resetLayoutHelp: 'Reset node positions in this saved view',
      delete: 'Delete',
      addMyWork: 'Add "my work"',
      selectWork: 'Select work',
      addMyWorkDescription: 'Create a node for your own work. It is saved in the library and can reference other documents.',
      noWorksRegisteredPrefix: 'No works registered, go to',
      noWorksRegisteredSuffix: 'to create a new work',
      addToMap: 'Add to map',
      workName: 'Work name',
      workNamePlaceholder: 'My article draft',
      name: 'Name',
      workspaceNote: 'Workspace note',
      workspaceNotePlaceholder: 'Why this map exists, what this subset means, or what to review next.',
      searchDocumentsPlaceholder: 'Search documents...',
      searchAndLinkPlaceholder: 'Search and add a document to link...',
      noMatchingDocument: 'No matching document found.',
      selectReferenceTarget: 'Select the document this one references, or search to add it',
      selectCitationTarget: 'Select the document that references this one, or search to add it',
      deleteNode: 'Hide node',
      deleteAllLinks: 'Delete all links',
      removeLinkMenu: 'Break link',
      invertLinkMenu: 'Invert link',
      relationDetails: 'Relation details',
      relationDetailsDescription: 'Select a document to inspect it, or click a connection to review or remove the relation.',
      relation: 'Relation',
      relationDescription: 'Review this persisted link between two documents.',
      closeDetails: 'Close details',
      citingDocument: 'Citing document',
      referencedDocument: 'Referenced document',
      makesReferenceTo: 'Makes reference to',
      isReferencedBy: 'Is referenced by',
      reverseLinkDirection: 'Reverse link direction',
      reverseLinkDirectionHelp: 'Swap which document points to the other',
      breakLink: 'Break link',
      breakLinkHelp: 'Permanently remove this relationship between the two documents',
      otherLinks: 'Other links',
      hideFromMap: 'Hide',
      physicalBook: 'Physical book',
      myWorkType: 'My work',
      pdfDocument: 'PDF document',
      author: 'Author',
      abstract: 'Abstract',
      collapse: 'Collapse',
      expand: 'Expand',
      none: 'none',
      addOrConnect: 'Add or connect linked documents',
      addReference: 'Add reference',
      addReferenceHelp: 'Link this document to one it references',
      addCitation: 'Add citation',
      addCitationHelp: 'Link a document that cites this one',
      findDocument: 'Find document',
      findDocumentHelp: 'Search this map and jump to a matching node.',
      searchTitlesInMap: 'Search titles in this map',
      jumpToMatchingDocument: 'Jump to matching document',
      filterLayout: 'Filters & layout',
      filterLayoutHelp: 'Show graph filters, layout options, and quick tools',
      expandControls: 'Expand',
      collapseControls: 'Collapse',
      appearance: 'Appearance',
      appearanceDescription: 'Control how documents look in the map.',
      nodeColors: 'Node colors',
      libraryColors: 'Library',
      yearColors: 'Year',
      density: 'Density',
      status: 'Status',
      component: 'Component',
      nodeSize: 'Node size',
      uniform: 'Uniform',
      inboundCitations: 'Inbound citations',
      totalDegree: 'Total degree',
      focus: 'Focus',
      focusDescription: 'Limit the view around the selected document.',
      focusType: 'Focus type',
      fullGraph: 'Full graph',
      oneHopNeighbors: '1-hop neighbors',
      twoHopNeighbors: '2-hop neighbors',
      hideIsolated: 'Hide isolated documents',
      hideIsolatedDescription: 'Remove documents with no visible links.',
      years: 'Years',
      yearsDescription: 'Filter visible documents by publication year.',
      from: 'From',
      to: 'To',
      any: 'Any',
    },
    metadataFields: {
      title: 'Title',
      authors: 'Authors',
      year: 'Year',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Publisher',
      citationKey: 'Citation key',
      abstract: 'Abstract',
      untitledDocument: 'Untitled document',
      queuePosition: '{current} of {total}',
      allCompleteDescription: 'All DOI-backed documents in {library} look complete.',
      noMissingDescription: 'No documents without a DOI fetch option are waiting in {library}.',
    },
    common: {
      previous: 'Previous',
      next: 'Next',
      goToPreviousPage: 'Go to previous page',
      goToNextPage: 'Go to next page',
      currentPage: 'Current page',
      morePages: 'More pages',
      unread: 'Unread',
      reading: 'Reading',
      finished: 'Finished',
      missing: 'Missing',
      partial: 'Partial',
      complete: 'Complete',
      ocrPending: 'OCR pending',
      processing: 'Processing',
      ocrComplete: 'OCR complete',
      ocrFailed: 'OCR failed',
      nativeText: 'Native text',
      new: 'NEW',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },

  'pt-BR': {
    nav: {
      home: 'Início',
      search: 'Busca',
      libraries: 'Bibliotecas',
      reader: 'Leitor',
      references: 'Minhas referências',
      notes: 'Notas',
      maps: 'Mapas',
      metadata: 'Metadados',
      reports: 'Relatórios',
      libraryGroup: 'Bibliotecas',
      researchWorkspace: 'Espaço de pesquisa',
      expandSidebar: 'Expandir barra lateral',
      collapseSidebar: 'Recolher barra lateral',
    },
    topBar: {
      searchPlaceholder: 'Buscar',
      command: 'Comandos',
      toggleTheme: 'Alternar tema',
      openSettings: 'Abrir configurações',
    },
    commandBar: {
      placeholder: 'Digite um comando ou pesquise...',
      empty: 'Nenhum resultado local encontrado.',
      navigation: 'Navegação',
      actions: 'Ações',
      libraries: 'Bibliotecas',
      recentDocuments: 'Documentos recentes',
      toggleTheme: 'Alternar tema',
      openSettings: 'Abrir configurações',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Solte PDFs para importar',
      dropDescription: 'O REFX abrirá Bibliotecas e continuará a importação lá.',
    },
    appProvider: {
      loadingWorkspace: 'Carregando espaço de trabalho...',
      welcomeTitle: 'Bem-vindo ao REFX',
      welcomeDescription: 'Defina seu nome para personalizar o painel.',
      yourName: 'Seu nome',
      namePlaceholder: 'Digite seu nome',
      dontAskAgain: 'Não perguntar novamente',
      continueWithoutName: 'Continuar sem nome',
      continue: 'Continuar',
    },
    settings: {
      title: 'Configurações',
      subtitle: 'Preferências deste dispositivo.',
      adjustLocalBehavior: 'Ajuste o comportamento local.',
      general: 'Geral',
      display: 'Aparência',
      processing: 'Processamento',
      data: 'Dados',
      about: 'Sobre',
      profileTitle: 'Perfil',
      profileDescription: 'Nome usado em seu espaço de trabalho.',
      yourName: 'Seu nome',
      yourNamePlaceholder: 'Digite seu nome',
      yourNameHelp: 'Deixe em branco para uma saudação impessoal. Você pode mudar isso depois.',
      language: 'Idioma',
      appearanceTitle: 'Aparência',
      appearanceDescription: 'Aparência deste dispositivo.',
      theme: 'Tema',
      fontSize: 'Tamanho da fonte',
      appUpdates: 'Atualizações do app',
      appUpdatesDescription: 'Verifique versões assinadas publicadas no GitHub.',
      checkAutomatically: 'Verificar automaticamente',
      checkAutomaticallyHelp: 'Procurar atualizações quando o REFX iniciar.',
      checking: 'Verificando...',
      checkForUpdates: 'Verificar atualizações',
      downloadInstall: 'Baixar e instalar',
      latestVersion: 'Você está na versão mais recente.',
      updateAvailable: 'Refx {version} está disponível.',
      unableToCheckForUpdates: 'Não foi possível verificar atualizações.',
      preparingUpdate: 'Preparando atualização...',
      updateInstallFailed: 'A instalação da atualização falhou.',
    },
    updateDialog: {
      title: 'Atualização disponível',
      descriptionVersion: 'Refx {version} está pronto para instalar.',
      descriptionFallback: 'Uma nova versão do Refx está disponível.',
      published: 'Publicado {value}',
      releaseNotes: 'Notas da versão',
      noNotes: 'Nenhuma nota de versão fornecida.',
      later: 'Mais tarde',
      installing: 'Instalando...',
      downloadInstall: 'Baixar e instalar',
      downloading: 'Baixando atualização...',
      downloadingKb: 'Baixando atualização... {size} KB',
      downloadingProgress: 'Baixando atualização... {downloaded} / {total} KB',
      installingStatus: 'Instalando atualização...',
      restarting: 'Reiniciando...',
    },
    home: {
      totalDocuments: 'Total de documentos',
      quickActions: 'Minhas bibliotecas',
      recentActivity: 'Atividade recente',
      noActivity: 'Ainda não há atividade',
      noActivityDescription: 'Importe documentos, adicione notas ou crie destaques para montar seu feed de atividade.',
      openLibraries: 'Abrir Bibliotecas',
      libraryCreated: 'Biblioteca criada',
      documentAdded: 'Documento adicionado à biblioteca',
      noteCreated: 'Nota criada',
      highlightCreated: 'Destaque criado',
      annotationCreated: 'Anotação criada',
      finishedReading: 'Leitura concluída',
      untitledNote: 'Nota sem título',
      libraryFallback: 'Biblioteca',
      bundledActivitySummary: 'Várias ações, clique para ver mais',
      page: 'Página {page}',
      minutesAgo: 'há {count} min',
      hoursAgo: 'há {count} h',
      daysAgo: 'há {count} d',
      welcomeBackNamed: 'Bem-vindo de volta, {name}',
      ideasTodayNamed: 'Quais são suas ideias hoje, {name}?',
      goodToSeeNamed: 'Bom ver você novamente, {name}',
      exploringTodayNamed: 'O que você está explorando hoje, {name}?',
      backAtItNamed: 'De volta ao trabalho, {name}',
      attentionTodayNamed: 'O que merece sua atenção hoje, {name}?',
      moveForwardNamed: 'O que você quer avançar hoje, {name}?',
      welcomeBack: 'Bem-vindo de volta',
      ideasToday: 'Quais são suas ideias hoje?',
      goodToSee: 'Bom ver você novamente',
      exploringToday: 'O que você está explorando hoje?',
      backAtIt: 'De volta ao trabalho',
      attentionToday: 'O que merece sua atenção hoje?',
      moveForwardToday: 'O que você quer avançar hoje?',
    },
    libraries: {
      allLibraries: 'Todas as bibliotecas',
      search: 'Buscar',
      filters: 'Filtros',
      library: 'Biblioteca',
      import: 'Importar',
      importing: 'Importando...',
      book: 'Livro',
      noDocuments: 'Nenhum documento encontrado',
      noDocumentsFiltered: 'Tente ajustar os filtros ou a busca.',
      noDocumentsEmpty: 'Importe PDFs ou registre um livro para começar.',
      importPdfs: 'Importar PDFs',
      importingPdfs: 'Importando PDFs...',
      registerPhysicalBook: 'Registrar livro físico',
      registerPhysicalBookDescription: 'Adicione um livro não-PDF a esta biblioteca para capturar notas por página ou capítulo.',
      title: 'Título',
      authors: 'Autores',
      authorsPlaceholder: 'Nomes dos autores separados por vírgula',
      year: 'Ano',
      isbn: 'ISBN',
      publisher: 'Editora',
      description: 'Descrição',
      descriptionPlaceholder: 'Notas ou resumo opcionais',
      bookPhoto: 'Foto do livro',
      bookPhotoDescription: 'Opcional. Adicione uma foto da capa deste computador ou leia um QR code para enviar do telefone.',
      noPhoto: 'Nenhuma foto selecionada ainda',
      uploadFromPc: 'Enviar do PC',
      addFromPhone: 'Adicionar do telefone',
      preparingQr: 'Preparando QR...',
      removePhoto: 'Remover foto',
      scanWithPhone: 'Escaneie com o telefone',
      sameNetwork: 'Mantenha o app desktop aberto. O telefone e o computador precisam estar na mesma rede local.',
      cancel: 'Cancelar',
      registering: 'Registrando...',
      registerBook: 'Registrar livro',
      localLibrary: 'Biblioteca local',
      documentsCount: '{count} documentos',
      sortAdded: 'Data de adição',
      sortOpened: 'Última abertura',
      sortTitle: 'Título',
      sortAuthors: 'Autores',
      sortYear: 'Ano',
      sortRating: 'Avaliação',
      deduplicate: 'Desduplicar',
      deduplicateDialogTitle: 'Verificador de duplicados',
      deduplicateDialogDescription: 'Revise possíveis duplicados em {library} por DOI, nome do arquivo e tamanho exato.',
      deduplicateDialogDescriptionFallback: 'Revise possíveis duplicados por DOI, nome do arquivo e tamanho exato.',
      scanningDuplicates: 'Verificando duplicados nesta biblioteca...',
      duplicateScanFailed: 'Não foi possível verificar duplicados agora.',
      noDuplicatesFound: 'Nenhum grupo duplicado encontrado nesta biblioteca.',
      duplicateDocumentsCount: '{count} documentos',
      activeFilters: '{count} filtro{suffix}',
      clearFilters: 'Limpar',
      hasComments: 'Com comentários',
      hasNotes: 'Com notas',
      tags: 'Tags',
      noLocalTags: 'Nenhuma tag local disponível.',
      duplicateDoi: 'Correspondência por DOI',
      duplicateFilename: 'Correspondência por nome do arquivo',
      duplicateFileSize: 'Correspondência por tamanho exato',
      duplicateFileSizeValue: '{size} bytes',
      keepDocument: 'Manter:',
      missingDoi: 'DOI ausente',
      mergeDuplicates: 'Mesclar duplicados',
      mergingDuplicates: 'Mesclando...',
      openDocument: 'Abrir',
      close: 'Fechar',
      scanning: 'Verificando...',
      rescan: 'Verificar novamente',
      importDocuments: 'Importando documentos',
      showingRange: 'Mostrando {start}–{end} de {total}',
    },
    documentTable: {
      favorite: 'Favorito',
      title: 'Título',
      authors: 'Autores',
      tags: 'Tags',
      year: 'Ano',
      status: 'Status',
      metadata: 'Metadados',
      comments: 'Comentários',
      rating: 'Avaliação',
      fetchPossible: 'Busca possível',
      readingStatus: 'Status de leitura',
      openComments: 'Abrir comentários',
      notes: '{count} notas',
      columns: 'Colunas',
      visibleColumns: 'Colunas visíveis',
      columnOrder: 'Ordem das colunas',
      generateSuggestions: 'Gerar sugestões',
    },
    notesPage: {
      searchNotes: 'Buscar notas',
      allLibraries: 'Todas as bibliotecas',
      sortTimestamp: 'Ordenar por data',
      sortPage: 'Ordenar por página',
      newNote: 'Nova nota',
      unlinkedNotes: 'Notas sem vínculo',
      untitledNote: 'Nota sem título',
      noContent: 'Sem conteúdo ainda.',
      noNotesForFilters: 'Nenhuma nota corresponde aos filtros atuais.',
      standaloneNote: 'Nota independente',
      seeInDocument: 'Ver no documento',
      updated: 'Atualizado {value}',
      openBookNotes: 'Abrir notas do livro',
      openDetails: 'Abrir detalhes',
      openReader: 'Abrir no leitor',
      reset: 'Redefinir',
      saving: 'Salvando...',
      save: 'Salvar',
      selectNote: 'Selecione uma nota',
      newNoteTitle: 'Nova nota',
    },
    readerIndex: {
      emptyTitle: 'Nenhum documento para ler',
      emptyDescription: 'Importe PDFs e abra um documento para montar sua fila de leitura local.',
      goLibraries: 'Ir para Bibliotecas',
      title: 'Leitor',
      subtitle: 'Continue de onde parou ou volte aos arquivos recentes.',
      continueReading: 'Continuar leitura',
      continueLabel: 'Continuar leitura',
      recentlyOpened: 'Abertos recentemente',
      unknownAuthor: 'Autor desconhecido',
    },
    readerView: {
      loadingPdf: 'Carregando PDF...',
      openingPdf: 'Abrindo PDF...',
      renderingPage: 'Renderizando página {page}...',
      pdfUnavailable: 'PDF indisponível.',
      importPdf: 'Importar PDF...',
      runningOcr: 'Executando OCR...',
      runOcr: 'Executar OCR',
      search: 'Busca',
      keywordOrPhrase: 'Palavra-chave ou frase',
      previous: 'Anterior',
      next: 'Próxima',
      noMatchesKeyword: 'Nenhuma ocorrência encontrada para esta palavra-chave.',
      notes: 'Notas',
      cancel: 'Cancelar',
      newNote: 'Nova nota',
      moveBalloon: 'Mover marcador',
      choosePosition: 'Escolher posição',
      writeNote: 'Escreva sua nota',
      saving: 'Salvando...',
      saveNote: 'Salvar nota',
      createNote: 'Criar nota',
      notesOnPage: '{count} nota{suffix} nesta página',
      edit: 'Editar',
      delete: 'Excluir',
      noNoteText: 'Sem texto na nota ainda.',
      noNotesPage: 'Ainda não há notas nesta página.',
      deleteNoteTitle: 'Excluir nota?',
      deleteNoteDescription: 'Isso removerá permanentemente {label} deste documento.',
      deleteNoteDescriptionFallback: 'Isso removerá permanentemente esta nota do documento.',
      clickOrDrawNote: 'Clique ou selectione',
      drawHighlight: 'Selecione para destacar',
      exactRegion: 'Região exata',
      pageFallback: 'Fallback por página',
      occurrence: 'Ocorrência {index}',
      approxPage: 'Página aprox.',
    },
    metadataPage: {
      workspace: 'Espaço de metadados',
      title: 'Metadados',
      subtitle: 'Revise correspondências por DOI e corrija documentos incompletos por biblioteca.',
      back: 'Voltar',
      library: 'Biblioteca',
      selectLibrary: 'Selecione uma biblioteca',
      fetchPossible: 'Busca possível',
      missing: 'Ausente',
      noLibrary: 'Nenhuma biblioteca selecionada',
      noLibraryDescription: 'Escolha uma biblioteca para começar a revisar metadados.',
      noFetchQueue: 'Sem documentos com busca por DOI disponível',
      noMissingQueue: 'Sem documentos com metadados ausentes',
      openDetails: 'Abrir detalhes',
      save: 'Salvar',
      saving: 'Salvando...',
      doiReview: 'Revisão de DOI',
      doiReviewDescription: 'Revise candidatos por DOI e escolha o melhor resultado.',
      manualReview: 'Revisão manual',
      manualReviewDescription: 'Percorra documentos que ainda precisam de limpeza manual de metadados.',
      refresh: 'Atualizar',
      searching: 'Buscando...',
      searchAcrossProviders: 'Buscando por DOI em Semantic Scholar, OpenAlex e Crossref...',
      noCandidates: 'Nenhum candidato de metadados encontrado para este DOI.',
      fillMissing: 'Preencher ausentes',
      applyCandidate: 'Aplicar candidato',
      manualQueueHelp: 'Focado em limpeza manual. Edite os campos à esquerda, salve e passe para o próximo documento.',
    },
    searchPage: {
      title: 'Busca',
      subtitle: 'Busca indexada em toda a biblioteca com MiniSearch local.',
      subtitleCompact: 'Busque em toda a sua biblioteca.',
      advancedFilters: 'Filtros avançados',
      advancedFiltersDescription: 'Monte consultas em grupos com lógica AND/OR e execute no escopo da biblioteca selecionada.',
      advancedFiltersCompact: 'Modo de busca, filtros e regras de correspondência.',
      queryMode: 'Modo de consulta',
      queryModeHelp: 'Simples é melhor para buscas rápidas. Complexo permite montar consultas por grupos e frases.',
      simple: 'Simples',
      complex: 'Complexo',
      keywordQuery: 'Consulta por palavras-chave',
      keywordQueryHelp: 'A busca simples aceita frases entre aspas. No modo complexo, cada palavra-chave é tratada como uma frase.',
      addGroup: 'Adicionar grupo',
      quickSearch: 'Busca rápida',
      quickSearchPlaceholder: 'Buscar',
      search: 'Buscar',
      simpleHelp: 'Pressione Enter ou Buscar. Use aspas para frases exatas.',
      betweenGroups: 'Entre grupos',
      everyGroup: 'Um documento deve satisfazer todos os grupos.',
      anyGroup: 'Um documento pode satisfazer qualquer grupo.',
      group: 'Grupo {index}',
      addKeywordPlaceholder: 'Adicionar palavra-chave a este grupo',
      add: 'Adicionar',
      addKeywordsHelpAnd: 'Cada palavra-chave é tratada como uma frase. O grupo corresponde apenas quando todas forem encontradas.',
      addKeywordsHelpOr: 'Cada palavra-chave é tratada como uma frase. O grupo corresponde quando qualquer uma for encontrada.',
      flexibility: 'Flexibilidade',
      strict: 'Rigorosa',
      balanced: 'Equilibrada',
      flexible: 'Flexível',
      veryFlexible: 'Muito flexível',
      flexibilityHelp: 'Maior flexibilidade permite variantes próximas, erros de digitação, palavras quebradas e aproximações.',
      library: 'Biblioteca',
      selectAll: 'Selecionar tudo',
      clearSelection: 'Limpar',
      selectedCount: '{count} selecionadas',
      allShort: 'Todas',
      readingStage: 'Status de leitura',
      anyStage: 'Qualquer status',
      metadataQuality: 'Qualidade dos metadados',
      anyStatus: 'Qualquer status',
      favoritesOnly: 'Mostrando apenas favoritos',
      filterFavorites: 'Apenas favoritos',
      persistentSearch: 'Busca indexada persistente',
      searchingDocs: 'Buscando {processed}/{total} documentos por {query}',
      resultsFor: '{count} resultado{suffix} para {query}',
      searchingBadge: 'Buscando',
      startTitle: 'Inicie uma busca',
      startDescriptionSimple: 'Digite na caixa de busca para consultar sua biblioteca indexada.',
      startDescriptionComplex: 'Adicione um ou mais grupos e pressione Buscar para varrer a biblioteca inteira.',
      loadingFallback: 'Consultando o índice local MiniSearch e resolvendo trechos do texto armazenado.',
      noMatchesTitle: 'Nenhum documento correspondente',
      noMatchesDescription: 'Tente aumentar a flexibilidade ou ampliar os filtros.',
      unknownAuthor: 'Autor desconhecido',
      page: 'Página {page}',
      openReader: 'Abrir no leitor',
      openDetails: 'Abrir detalhes',
      exactRegion: 'Região exata',
      pageFallback: 'Fallback por página',
      occurrence: 'Ocorrência {index}',
      approxPage: 'Página aprox.',
      noMatchesForKeyword: 'Nenhuma ocorrência encontrada para esta palavra-chave.',
      preparingIndex: 'Preparando o índice local de busca...',
      resultsReady: '{count} resultado{suffix} pronto',
    },
    documentDetailPage: {
      information: 'Informacoes do documento',
      tagsAndClassification: 'Tags e classificação ({count})',
      suggestedTags: 'Tags sugeridas ({count})',
      semanticClassification: 'Classificação semântica',
      classifyLocal: 'Classificar com heuristica local',
      reclassifyLocal: 'Reclassificar com heurística local',
      classifyAi: 'Classificar com IA a partir da mesma analise da primeira pagina usada nas tags',
      classificationDisabled: 'A classificacao semantica esta desativada nas Configuracoes.',
      classificationNeedsText: 'Este documento precisa de texto extraido ou OCR antes de poder ser classificado.',
      aiClassificationFinished: 'Classificação com IA concluida.',
      aiClassificationFailed: 'A classificação com IA falhou.',
      aiClassificationNotSaved: 'A classificação com IA não foi salva.',
      noClassificationSaved: 'Nenhuma classificação semântica salva para este documento.',
      referencesAndCitations: 'Referências e citações ({outgoing}/{incoming})',
      findReferences: 'Encontrar refêrencias',
    },
    referencesPage: {
      title: 'Minhas Referências',
      subtitle: 'Monte bibliografias reutilizáveis para seus trabalhos, combine documentos correspondentes e referencias livres, e copie tudo no estilo desejado.',
      citationStyle: 'Estilo de citação',
      addWork: 'Adicionar trabalho',
      works: 'Trabalhos',
      worksHelp: 'Escolha um item de Meu trabalho ou crie um novo.',
      selectWork: 'Selecionar trabalho',
      referencesCount: '{count} referencia{suffix}',
      noWorkSelected: 'Nenhum trabalho selecionado',
      selectWorkToManage: 'Selecione um trabalho para gerenciar sua bibliografia.',
      createFirstWork: 'Crie seu primeiro trabalho para comecar a coletar referencias.',
      bibliography: 'Bibliografia',
      bibliographyHelp: 'Arraste para reordenar. Copie qualquer entrada no formato {style}.',
      addReference: 'Adicionar referencia',
      addReferenceDescription: 'Associe um dos seus documentos quando possivel, ou salve uma referencia livre que exista apenas nesta bibliografia.',
      recheckMatches: 'Verificar correspondencias',
      loadingReferences: 'Carregando referencias...',
      noReferencesYet: 'Ainda nao ha referencias',
      noReferencesYetDescription: 'Adicione referencias para montar a bibliografia deste trabalho.',
      existsInLibraries: 'Existe nas bibliotecas',
      copyReference: 'Copiar referencia',
      removeReference: 'Remover referencia',
      addWorkDescription: 'Crie um item de Meu trabalho que possa conter uma bibliografia ordenada.',
      workName: 'Nome do trabalho',
      workNamePlaceholder: 'Rascunho do meu artigo',
      createWork: 'Criar trabalho',
      deleteWork: 'Excluir trabalho',
      deleteWorkDescription: 'Isto removera permanentemente "{title}" e suas entradas bibliograficas vinculadas deste trabalho.',
      deleteWorkDescriptionFallback: 'Isto removera permanentemente este trabalho e suas entradas bibliograficas vinculadas.',
      cancel: 'Cancelar',
      type: 'Tipo',
      referenceType: 'Tipo de referencia',
      referenceTypeArticle: 'Artigo',
      referenceTypeBook: 'Livro',
      referenceTypeConference: 'Conferencia',
      referenceTypeThesis: 'Tese',
      referenceTypeReport: 'Relatorio',
      referenceTypeOnline: 'Online',
      referenceTypeMisc: 'Outro',
      referenceTitlePlaceholder: 'Titulo da referencia',
      authorsPlaceholder: 'Autor Um; Autor Dois',
      publisherSource: 'Editora / fonte',
      publisherPlaceholder: 'Editora',
      journal: 'Periodico',
      journalPlaceholder: 'Nome do periodico',
      booktitleCollection: 'Titulo do livro / coletanea',
      booktitlePlaceholder: 'Livro ou anais',
      url: 'URL',
      urlPlaceholder: 'https://example.org',
      abstractNote: 'Resumo / nota',
      abstractPlaceholder: 'Resumo ou nota opcional',
      matchingSuggestions: 'Sugestoes de correspondencia',
      matchingSuggestionsDescription: 'Os documentos existentes sao sugeridos primeiro por DOI, depois por titulo, autor e ano.',
      matchingSuggestionsEmpty: 'Digite um titulo, DOI ou autor para ver documentos correspondentes da sua biblioteca.',
      matchPercent: 'Correspondencia {percent}%',
      alreadyInWork: 'Ja esta neste trabalho',
      referenceWillBeLinked: 'Esta referencia sera vinculada a um documento existente se a correspondencia continuar valida.',
      freeformReferenceHelp: 'Voce ainda pode salvar uma referencia livre sem correspondencia.',
      removeReferenceConfirm: 'Remover esta referencia do trabalho atual?',
      removeReferenceConfirmNamed: 'Remover "{title}" deste trabalho?',
      remove: 'Remover',
      couldNotLoadReferences: 'Nao foi possivel carregar as referencias.',
      couldNotLoadWorkReferences: 'Nao foi possivel carregar as referencias do trabalho.',
      selectWorkBeforeAddingReferences: 'Selecione um trabalho antes de adicionar referencias.',
      workNameRequired: 'O nome do trabalho e obrigatorio.',
      createLibraryBeforeAddingWork: 'Crie uma biblioteca antes de adicionar um trabalho.',
      createdWork: '"{title}" foi criado.',
      couldNotCreateWork: 'Nao foi possivel criar o trabalho.',
      deletedWork: '"{title}" foi excluido.',
      couldNotDeleteWork: 'Nao foi possivel excluir o trabalho.',
      addedDocumentToWork: '"{title}" foi adicionado a este trabalho.',
      couldNotAddReference: 'Nao foi possivel adicionar a referencia.',
      referenceTitleRequired: 'O titulo da referencia e obrigatorio.',
      referenceAdded: 'Referencia adicionada.',
      couldNotCopyReference: 'Nao foi possivel copiar a referencia.',
      referenceRemovedFromWork: 'Referencia removida deste trabalho.',
      couldNotRemoveReference: 'Nao foi possivel remover a referencia.',
      referenceMatchesRefreshed: 'Correspondencias de referencias atualizadas.',
      couldNotRefreshMatches: 'Nao foi possivel atualizar as correspondencias.',
      couldNotReorderReferences: 'Nao foi possivel reordenar as referencias.',
    },
    mapsPage: {
      title: 'Mapas',
      subtitle: 'Explore relações, organize vistas salvas e crie links direto no canvas.',
      workspace: 'Espaço de trabalho',
      workingMap: 'Selecionar mapa',
      workingMapDescription: 'Escolha um dos mapas salvos desta biblioteca.',
      mapView: 'Vista do mapa',
      canvasEditor: 'Editor do mapa',
      addReferencedDocument: 'Adicionar documento referenciado',
      addCitingDocument: 'Adicionar documento citante',
      addDocument: 'Adicionar documento',
      addDocumentHelp: 'Busque na biblioteca atual e traga outro documento para este mapa.',
      addDocumentLinkHelp: 'Busque na biblioteca, adicione o documento ao mapa e conecte tudo em um único passo.',
      findReferencedDocument: 'Encontrar documento referenciado',
      findCitingDocument: 'Encontrar documento citante',
      addDocumentToMap: 'Adicionar documento ao mapa',
      myWork: 'Meu trabalho',
      noDocumentsControls: 'Nenhum documento corresponde aos controles atuais.',
      noLinksControls: 'Nenhum link corresponde aos controles atuais.',
      saveGraphView: 'Salvar vista do mapa',
      saveGraphViewDescription: 'Salve o mapa atual como um espaço reutilizável com filtros, subconjunto e layout.',
      editGraphView: 'Editar vista do mapa',
      editGraphViewDescription: 'Renomeie este espaço ou atualize a descrição sem alterar as relações dos documentos.',
      cancel: 'Cancelar',
      saveView: 'Salvar vista',
      saveChanges: 'Salvar alterações',
      saveAsNewView: 'Salvar como nova vista',
      saveCurrentView: 'Salvar alterações',
      saveCurrentViewHelp: 'Atualizar a vista salva atualmente selecionada',
      saveNewViewHelp: 'Salvar este layout e filtros como uma nova vista reutilizável',
      newMap: 'Novo mapa',
      rebuildLayout: 'Reconstruir layout',
      rebuildLayoutHelp: 'Reorganizar os nós visíveis para melhorar o layout',
      deleteMap: 'Excluir mapa',
      showControls: 'Mostrar controles',
      hideControls: 'Ocultar controles',
      renameView: 'Renomear vista',
      duplicateView: 'Duplicar',
      resetLayout: 'Redefinir layout',
      resetLayoutHelp: 'Redefinir as posições dos nós nesta vista salva',
      delete: 'Excluir',
      addMyWork: 'Adicionar "meu trabalho"',
      noWorksRegisteredPrefix: 'Nenhum trabalho cadastrado, vá para',
      noWorksRegisteredSuffix: 'para criar um novo trabalho',
      selectWork: 'Selecionar trabalho',
      addMyWorkDescription: 'Crie um nó para seu próprio trabalho. Ele fica salvo na biblioteca e pode referenciar outros documentos.',
      addToMap: 'Adicionar ao mapa',
      workName: 'Nome do trabalho',
      workNamePlaceholder: 'Meu rascunho de artigo',
      name: 'Nome',
      workspaceNote: 'Nota do espaço',
      workspaceNotePlaceholder: 'Por que este mapa existe, o que este subconjunto significa ou o que revisar depois.',
      searchDocumentsPlaceholder: 'Buscar documentos...',
      searchAndLinkPlaceholder: 'Buscar e adicionar um documento para vincular...',
      noMatchingDocument: 'Nenhum documento correspondente encontrado.',
      selectReferenceTarget: 'Selecione o documento ao qual este faz referência, ou pesquise para adicioná-lo',
      selectCitationTarget: 'Selecione o documento que referencia este, ou pesquise para adicioná-lo',
      deleteNode: 'Ocultar nó',
      deleteAllLinks: 'Excluir todos os links',
      removeLinkMenu: 'Quebrar link',
      invertLinkMenu: 'Inverter link',
      relationDetails: 'Detalhes da relação',
      relationDetailsDescription: 'Selecione um documento para inspecioná-lo ou clique em uma conexão para revisar ou remover a relação.',
      relation: 'Relação',
      relationDescription: 'Revise este link persistido entre dois documentos.',
      closeDetails: 'Fechar detalhes',
      citingDocument: 'Documento citante',
      referencedDocument: 'Documento referenciado',
      makesReferenceTo: 'Faz referência a',
      isReferencedBy: 'É citado por',
      reverseLinkDirection: 'Inverter direção do link',
      reverseLinkDirectionHelp: 'Trocar qual documento aponta para o outro',
      breakLink: 'Quebrar link',
      breakLinkHelp: 'Remover permanentemente esta relação entre os dois documentos',
      otherLinks: 'Outros links',
      hideFromMap: 'Ocultar',
      physicalBook: 'Livro físico',
      myWorkType: 'Meu trabalho',
      pdfDocument: 'Documento PDF',
      author: 'Autor',
      abstract: 'Resumo',
      collapse: 'Recolher',
      expand: 'Expandir',
      none: 'nenhum',
      addOrConnect: 'Adicionar ou conectar documentos vinculados',
      addReference: 'Adicionar referência',
      addReferenceHelp: 'Vincular este documento a outro que ele referencia',
      addCitation: 'Adicionar citação',
      addCitationHelp: 'Vincular um documento que cita este',
      findDocument: 'Encontrar documento',
      findDocumentHelp: 'Busque neste mapa e pule para um nó correspondente.',
      searchTitlesInMap: 'Buscar títulos neste mapa',
      jumpToMatchingDocument: 'Ir para documento correspondente',
      filterLayout: 'Filtros e layout',
      filterLayoutHelp: 'Mostrar filtros do mapa, opções de layout e ferramentas rápidas',
      expandControls: 'Expandir',
      collapseControls: 'Recolher',
      appearance: 'Aparência',
      appearanceDescription: 'Controle como os documentos aparecem no mapa.',
      nodeColors: 'Cores dos nós',
      libraryColors: 'Biblioteca',
      yearColors: 'Ano',
      density: 'Densidade',
      status: 'Status',
      component: 'Componente',
      nodeSize: 'Tamanho do nó',
      uniform: 'Uniforme',
      inboundCitations: 'Citações recebidas',
      totalDegree: 'Grau total',
      focus: 'Foco',
      focusDescription: 'Limite a visualização ao redor do documento selecionado.',
      focusType: 'Tipo de foco',
      fullGraph: 'Mapa completo',
      oneHopNeighbors: 'Conectados diretamente',
      twoHopNeighbors: 'Conectados diretamente +1',
      hideIsolated: 'Ocultar documentos isolados',
      hideIsolatedDescription: 'Remover documentos sem links visíveis.',
      years: 'Anos',
      yearsDescription: 'Filtre os documentos visíveis por ano de publicação.',
      from: 'De',
      to: 'Até',
      any: 'Qualquer',
    },
    metadataFields: {
      title: 'Título',
      authors: 'Autores',
      year: 'Ano',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Editora',
      citationKey: 'Chave de citação',
      abstract: 'Resumo',
      untitledDocument: 'Documento sem título',
      queuePosition: '{current} de {total}',
      allCompleteDescription: 'Todos os documentos com DOI em {library} parecem completos.',
      noMissingDescription: 'Não há documentos sem opção de busca por DOI aguardando em {library}.',
    },
    common: {
      previous: 'Anterior',
      next: 'Próxima',
      goToPreviousPage: 'Ir para a página anterior',
      goToNextPage: 'Ir para a próxima página',
      currentPage: 'Página atual',
      morePages: 'Mais páginas',
      unread: 'Não lido',
      reading: 'Lendo',
      finished: 'Concluído',
      missing: 'Ausente',
      partial: 'Parcial',
      complete: 'Completo',
      ocrPending: 'OCR pendente',
      processing: 'Processando',
      ocrComplete: 'OCR concluído',
      ocrFailed: 'OCR falhou',
      nativeText: 'Texto nativo',
      new: 'NOVO',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },

  fr: {
    nav: {
      home: 'Accueil',
      search: 'Recherche',
      libraries: 'Bibliothèques',
      reader: 'Lecteur',
      references: 'Mes références',
      notes: 'Notes',
      maps: 'Cartes',
      metadata: 'Métadonnées',
      reports: 'Rapports',
      libraryGroup: 'Bibliothèques',
      researchWorkspace: 'Espace de recherche',
      expandSidebar: 'Développer la barre latérale',
      collapseSidebar: 'Réduire la barre latérale',
    },
    topBar: {
      searchPlaceholder: 'Rechercher',
      command: 'Commandes',
      toggleTheme: 'Changer de thème',
      openSettings: 'Ouvrir les paramètres',
    },
    commandBar: {
      placeholder: 'Tapez une commande ou lancez une recherche...',
      empty: 'Aucun résultat local trouvé.',
      navigation: 'Navigation',
      actions: 'Actions',
      libraries: 'Bibliothèques',
      recentDocuments: 'Documents récents',
      toggleTheme: 'Changer de thème',
      openSettings: 'Ouvrir les paramètres',
      docsCount: '{count} docs',
    },
    shell: {
      dropTitle: 'Déposez des PDF à importer',
      dropDescription: "REFX ouvrira Bibliothèques et poursuivra l'import là-bas.",
    },
    appProvider: {
      loadingWorkspace: "Chargement de l'espace de travail...",
      welcomeTitle: 'Bienvenue dans REFX',
      welcomeDescription: 'Définissez votre nom pour personnaliser le tableau de bord.',
      yourName: 'Votre nom',
      namePlaceholder: 'Saisissez votre nom',
      dontAskAgain: 'Ne plus demander',
      continueWithoutName: 'Continuer sans nom',
      continue: 'Continuer',
    },
    settings: {
      title: 'Paramètres',
      subtitle: 'Préférences de cet appareil.',
      adjustLocalBehavior: 'Ajustez le comportement local.',
      general: 'Général',
      display: 'Apparence',
      processing: 'Traitement',
      data: 'Données',
      about: 'À propos',
      profileTitle: 'Profil',
      profileDescription: 'Nom utilisé dans votre espace de travail.',
      yourName: 'Votre nom',
      yourNamePlaceholder: 'Saisissez votre nom',
      yourNameHelp: 'Laissez vide pour une salutation impersonnelle. Vous pouvez le modifier plus tard.',
      language: 'Langue',
      appearanceTitle: 'Apparence',
      appearanceDescription: 'Apparence de cet appareil.',
      theme: 'Thème',
      fontSize: 'Taille du texte',
      appUpdates: "Mises à jour de l'application",
      appUpdatesDescription: 'Vérifiez les versions signées publiées sur GitHub.',
      checkAutomatically: 'Vérifier automatiquement',
      checkAutomaticallyHelp: 'Rechercher des mises à jour au démarrage de REFX.',
      checking: 'Vérification...',
      checkForUpdates: 'Vérifier les mises à jour',
      downloadInstall: 'Télécharger et installer',
      latestVersion: 'Vous utilisez déjà la dernière version.',
      updateAvailable: 'Refx {version} est disponible.',
      unableToCheckForUpdates: 'Impossible de vérifier les mises à jour.',
      preparingUpdate: 'Préparation de la mise à jour...',
      updateInstallFailed: "L'installation de la mise à jour a échoué.",
    },
    updateDialog: {
      title: 'Mise à jour disponible',
      descriptionVersion: 'Refx {version} est prêt à être installé.',
      descriptionFallback: 'Une nouvelle version de Refx est disponible.',
      published: 'Publié {value}',
      releaseNotes: 'Notes de version',
      noNotes: 'Aucune note de version fournie.',
      later: 'Plus tard',
      installing: 'Installation...',
      downloadInstall: 'Télécharger et installer',
      downloading: 'Téléchargement de la mise à jour...',
      downloadingKb: 'Téléchargement de la mise à jour... {size} KB',
      downloadingProgress: 'Téléchargement de la mise à jour... {downloaded} / {total} KB',
      installingStatus: 'Installation de la mise à jour...',
      restarting: 'Redémarrage...',
    },
    home: {
      totalDocuments: 'Total des documents',
      quickActions: 'Mes bibliothèques',
      recentActivity: 'Activité récente',
      noActivity: 'Aucune activité pour le moment',
      noActivityDescription: 'Importez des documents, ajoutez des notes ou créez des surlignages pour alimenter votre activité.',
      openLibraries: 'Ouvrir Bibliothèques',
      libraryCreated: 'Bibliothèque créée',
      documentAdded: 'Document ajouté à la bibliothèque',
      noteCreated: 'Note créée',
      highlightCreated: 'Surlignage créé',
      annotationCreated: 'Annotation créée',
      finishedReading: 'Lecture terminée',
      untitledNote: 'Note sans titre',
      bundledActivitySummary: 'Plusieurs actions, cliquez pour en voir plus',
      libraryFallback: 'Bibliothèque',
      page: 'Page {page}',
      minutesAgo: 'il y a {count} min',
      hoursAgo: 'il y a {count} h',
      daysAgo: 'il y a {count} j',
      welcomeBackNamed: 'Bon retour, {name}',
      ideasTodayNamed: "Quelles sont vos idées aujourd'hui, {name} ?",
      goodToSeeNamed: 'Heureux de vous revoir, {name}',
      exploringTodayNamed: "Qu'explorez-vous aujourd'hui, {name} ?",
      backAtItNamed: 'De retour, {name}',
      attentionTodayNamed: "Qu'est-ce qui mérite votre attention aujourd'hui, {name} ?",
      moveForwardNamed: "Que voulez-vous faire avancer aujourd'hui, {name} ?",
      welcomeBack: 'Bon retour',
      ideasToday: "Quelles sont vos idées aujourd'hui ?",
      goodToSee: 'Heureux de vous revoir',
      exploringToday: "Qu'explorez-vous aujourd'hui ?",
      backAtIt: 'De retour',
      attentionToday: "Qu'est-ce qui mérite votre attention aujourd'hui ?",
      moveForwardToday: "Que voulez-vous faire avancer aujourd'hui ?",
    },
    libraries: {
      allLibraries: 'Toutes les bibliothèques',
      search: 'Rechercher',
      filters: 'Filtres',
      library: 'Bibliothèque',
      import: 'Importer',
      importing: 'Import...',
      book: 'Livre',
      noDocuments: 'Aucun document trouvé',
      noDocumentsFiltered: "Essayez d'ajuster les filtres ou la recherche.",
      noDocumentsEmpty: 'Importez des PDF ou enregistrez un livre pour commencer.',
      importPdfs: 'Importer des PDF',
      importingPdfs: 'Import des PDF...',
      registerPhysicalBook: 'Enregistrer un livre papier',
      registerPhysicalBookDescription: 'Ajoutez un livre non PDF à cette bibliothèque pour capturer des notes par page ou chapitre.',
      title: 'Titre',
      authors: 'Auteurs',
      authorsPlaceholder: 'Noms des auteurs séparés par des virgules',
      year: 'Année',
      isbn: 'ISBN',
      publisher: 'Éditeur',
      description: 'Description',
      descriptionPlaceholder: 'Notes ou résumé facultatifs',
      bookPhoto: 'Photo du livre',
      bookPhotoDescription: "Facultatif. Ajoutez une photo de couverture depuis cet ordinateur ou scannez un QR code pour l'envoyer depuis votre téléphone.",
      noPhoto: 'Aucune photo sélectionnée',
      uploadFromPc: 'Depuis le PC',
      addFromPhone: 'Depuis le téléphone',
      preparingQr: 'Préparation du QR...',
      removePhoto: 'Supprimer la photo',
      scanWithPhone: 'Scannez avec votre téléphone',
      sameNetwork: "Gardez l'application desktop ouverte. Le téléphone et l'ordinateur doivent être sur le même réseau local.",
      cancel: 'Annuler',
      registering: 'Enregistrement...',
      registerBook: 'Enregistrer le livre',
      localLibrary: 'Bibliothèque locale',
      documentsCount: '{count} documents',
      sortAdded: "Date d'ajout",
      sortOpened: 'Dernière ouverture',
      sortTitle: 'Titre',
      sortAuthors: 'Auteurs',
      sortYear: 'Année',
      sortRating: 'Note',
      deduplicate: 'Dédoublonner',
      deduplicateDialogTitle: 'Détecteur de doublons',
      deduplicateDialogDescription: 'Passez en revue les doublons possibles dans {library} par DOI, nom de fichier et taille exacte.',
      deduplicateDialogDescriptionFallback: 'Passez en revue les doublons possibles par DOI, nom de fichier et taille exacte.',
      scanningDuplicates: 'Recherche de doublons dans cette bibliothèque...',
      duplicateScanFailed: 'Impossible de vérifier les doublons pour le moment.',
      noDuplicatesFound: 'Aucun groupe en double trouvé dans cette bibliothèque.',
      duplicateDocumentsCount: '{count} documents',
      activeFilters: '{count} filtre{suffix}',
      clearFilters: 'Effacer',
      hasComments: 'Avec commentaires',
      hasNotes: 'Avec notes',
      tags: 'Tags',
      noLocalTags: 'Aucun tag local disponible.',
      duplicateDoi: 'Correspondance DOI',
      duplicateFilename: 'Correspondance du nom de fichier',
      duplicateFileSize: 'Correspondance par taille exacte',
      duplicateFileSizeValue: '{size} octets',
      keepDocument: 'Conserver :',
      missingDoi: 'DOI manquant',
      mergeDuplicates: 'Fusionner les doublons',
      mergingDuplicates: 'Fusion...',
      openDocument: 'Ouvrir',
      close: 'Fermer',
      scanning: 'Analyse...',
      rescan: 'Relancer',
      importDocuments: 'Import des documents',
      showingRange: 'Affichage {start}–{end} sur {total}',
    },
    documentTable: {
      favorite: 'Favori',
      title: 'Titre',
      authors: 'Auteurs',
      tags: 'Tags',
      year: 'Année',
      status: 'Statut',
      metadata: 'Métadonnées',
      comments: 'Commentaires',
      rating: 'Note',
      fetchPossible: 'Recherche possible',
      readingStatus: 'Statut de lecture',
      openComments: 'Ouvrir les commentaires',
      notes: '{count} notes',
      columns: 'Colonnes',
      visibleColumns: 'Colonnes visibles',
      columnOrder: 'Ordre des colonnes',
      generateSuggestions: 'Générer des suggestions',
    },
    notesPage: {
      searchNotes: 'Rechercher des notes',
      allLibraries: 'Toutes les bibliothèques',
      sortTimestamp: 'Trier par date',
      sortPage: 'Trier par page',
      newNote: 'Nouvelle note',
      unlinkedNotes: 'Notes sans lien',
      untitledNote: 'Note sans titre',
      noContent: 'Aucun contenu pour le moment.',
      noNotesForFilters: 'Aucune note ne correspond aux filtres actuels.',
      standaloneNote: 'Note autonome',
      seeInDocument: 'Voir dans le document',
      updated: 'Mis à jour {value}',
      openBookNotes: 'Ouvrir les notes du livre',
      openDetails: 'Ouvrir les détails',
      openReader: 'Ouvrir dans le lecteur',
      reset: 'Réinitialiser',
      saving: 'Enregistrement...',
      save: 'Enregistrer',
      selectNote: 'Sélectionnez une note',
      newNoteTitle: 'Nouvelle note',
    },
    readerIndex: {
      emptyTitle: 'Aucun document à lire',
      emptyDescription: 'Importez des PDF et ouvrez un document pour construire votre file de lecture locale.',
      goLibraries: 'Aller aux bibliothèques',
      title: 'Lecteur',
      subtitle: "Reprenez là où vous en étiez ou rouvrez un fichier récent.",
      continueReading: 'Poursuivre la lecture',
      continueLabel: 'Continuer la lecture',
      recentlyOpened: 'Ouverts récemment',
      unknownAuthor: 'Auteur inconnu',
    },
    readerView: {
      loadingPdf: 'Chargement du PDF...',
      openingPdf: 'Ouverture du PDF...',
      renderingPage: 'Rendu de la page {page}...',
      pdfUnavailable: 'PDF indisponible.',
      importPdf: 'Importer un PDF...',
      runningOcr: 'OCR en cours...',
      runOcr: "Lancer l'OCR",
      search: 'Recherche',
      keywordOrPhrase: 'Mot-clé ou expression',
      previous: 'Précédent',
      next: 'Suivant',
      noMatchesKeyword: 'Aucune occurrence trouvée pour ce mot-clé.',
      notes: 'Notes',
      cancel: 'Annuler',
      newNote: 'Nouvelle note',
      moveBalloon: 'Déplacer le marqueur',
      choosePosition: 'Choisir la position',
      writeNote: 'Écrivez votre note',
      saving: 'Enregistrement...',
      saveNote: 'Enregistrer la note',
      createNote: 'Créer la note',
      notesOnPage: '{count} note{suffix} sur cette page',
      edit: 'Modifier',
      delete: 'Supprimer',
      noNoteText: 'Aucun texte de note pour le moment.',
      noNotesPage: 'Aucune note sur cette page pour le moment.',
      deleteNoteTitle: 'Supprimer la note ?',
      deleteNoteDescription: 'Cela supprimera définitivement {label} de ce document.',
      deleteNoteDescriptionFallback: 'Cela supprimera définitivement cette note du document.',
      clickOrDrawNote: 'Cliquez ou dessinez une zone pour placer une note',
      drawHighlight: 'Dessinez une zone à surligner',
      exactRegion: 'Zone exacte',
      pageFallback: 'Repli par page',
      occurrence: 'Occurrence {index}',
      approxPage: 'Page approx.',
    },
    metadataPage: {
      workspace: 'Espace de métadonnées',
      title: 'Métadonnées',
      subtitle: 'Revoyez les correspondances DOI et corrigez les documents incomplets par bibliothèque.',
      back: 'Retour',
      library: 'Bibliothèque',
      selectLibrary: 'Choisir une bibliothèque',
      fetchPossible: 'Recherche possible',
      missing: 'Manquant',
      noLibrary: 'Aucune bibliothèque sélectionnée',
      noLibraryDescription: 'Choisissez une bibliothèque pour commencer la révision des métadonnées.',
      noFetchQueue: 'Aucun document avec une recherche DOI disponible',
      noMissingQueue: 'Aucun document avec des métadonnées manquantes',
      openDetails: 'Ouvrir les détails',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      doiReview: 'Révision DOI',
      doiReviewDescription: 'Revoyez les candidats basés sur le DOI et choisissez le meilleur résultat.',
      manualReview: 'Révision manuelle',
      manualReviewDescription: "Parcourez les documents qui ont encore besoin d'une correction manuelle.",
      refresh: 'Actualiser',
      searching: 'Recherche...',
      searchAcrossProviders: 'Recherche par DOI dans Semantic Scholar, OpenAlex et Crossref...',
      noCandidates: 'Aucun candidat de métadonnées trouvé pour ce DOI.',
      fillMissing: 'Compléter les champs manquants',
      applyCandidate: 'Appliquer le candidat',
      manualQueueHelp: "Focalisé sur le nettoyage manuel. Modifiez les champs à gauche, enregistrez puis passez au document suivant.",
    },
    searchPage: {
      title: 'Recherche',
      subtitle: 'Recherche indexée dans toute la bibliothèque avec MiniSearch local.',
      subtitleCompact: 'Recherchez dans toute votre bibliothèque.',
      advancedFilters: 'Filtres avancés',
      advancedFiltersDescription: 'Construisez des requêtes groupées avec la logique AND/OR puis lancez-les sur la bibliothèque choisie.',
      advancedFiltersCompact: 'Mode de recherche, filtres et règles de correspondance.',
      queryMode: 'Mode de requête',
      queryModeHelp: 'Le mode simple est idéal pour les recherches rapides. Le mode complexe permet de créer des groupes de phrases.',
      simple: 'Simple',
      complex: 'Complexe',
      keywordQuery: 'Requête par mots-clés',
      keywordQueryHelp: 'La recherche simple accepte les expressions entre guillemets. En mode complexe, chaque mot-clé est traité comme une phrase.',
      addGroup: 'Ajouter un groupe',
      quickSearch: 'Recherche rapide',
      quickSearchPlaceholder: 'Rechercher',
      search: 'Rechercher',
      simpleHelp: 'Appuyez sur Entrée ou Rechercher. Utilisez des guillemets pour les expressions exactes.',
      betweenGroups: 'Entre les groupes',
      everyGroup: 'Un document doit satisfaire tous les groupes.',
      anyGroup: "Un document peut satisfaire n'importe quel groupe.",
      group: 'Groupe {index}',
      addKeywordPlaceholder: 'Ajouter un mot-clé à ce groupe',
      add: 'Ajouter',
      addKeywordsHelpAnd: "Chaque mot-clé est traité comme une expression. Le groupe ne correspond que si tous sont trouvés.",
      addKeywordsHelpOr: "Chaque mot-clé est traité comme une expression. Le groupe correspond si l'un d'eux est trouvé.",
      flexibility: 'Souplesse',
      strict: 'Stricte',
      balanced: 'Équilibrée',
      flexible: 'Souple',
      veryFlexible: 'Très souple',
      flexibilityHelp: 'Une plus grande souplesse autorise les variantes proches, fautes de frappe, mots coupés et correspondances proches.',
      library: 'Bibliothèque',
      selectAll: 'Tout sélectionner',
      clearSelection: 'Effacer',
      selectedCount: '{count} sélectionnés',
      allShort: 'Toutes',
      readingStage: 'Statut de lecture',
      anyStage: "N'importe quel statut",
      metadataQuality: 'Qualité des métadonnées',
      anyStatus: "N'importe quel statut",
      favoritesOnly: 'Favoris uniquement',
      filterFavorites: 'Favoris uniquement',
      persistentSearch: 'Recherche indexée persistante',
      searchingDocs: 'Recherche de {processed}/{total} documents pour {query}',
      resultsFor: '{count} résultat{suffix} pour {query}',
      searchingBadge: 'Recherche',
      startTitle: 'Commencez une recherche',
      startDescriptionSimple: 'Tapez dans le champ de recherche pour interroger votre bibliothèque indexée.',
      startDescriptionComplex: "Ajoutez un ou plusieurs groupes puis appuyez sur Rechercher pour parcourir toute la bibliothèque.",
      loadingFallback: "Interrogation de l'index local MiniSearch et résolution des extraits à partir du texte stocké.",
      noMatchesTitle: 'Aucun document correspondant',
      noMatchesDescription: "Essayez d'augmenter la souplesse ou d'élargir les filtres.",
      unknownAuthor: 'Auteur inconnu',
      page: 'Page {page}',
      openReader: 'Ouvrir dans le lecteur',
      openDetails: 'Ouvrir les détails',
      exactRegion: 'Zone exacte',
      pageFallback: 'Repli par page',
      occurrence: 'Occurrence {index}',
      approxPage: 'Page approx.',
      noMatchesForKeyword: 'Aucune occurrence trouvée pour ce mot-clé.',
      preparingIndex: "Préparation de l'index de recherche local...",
      resultsReady: '{count} résultat{suffix} prêt',
    },
    documentDetailPage: {
      information: 'Informations du document',
      tagsAndClassification: 'Tags et classification ({count})',
      suggestedTags: 'Tags suggeres ({count})',
      semanticClassification: 'Classification semantique',
      classifyLocal: 'Classifier avec l heuristique locale',
      reclassifyLocal: 'Reclassifier avec l heuristique locale',
      classifyAi: 'Classifier avec l IA a partir de la meme analyse de premiere page que les tags IA',
      classificationDisabled: 'La classification semantique est desactivee dans les Parametres.',
      classificationNeedsText: 'Ce document a besoin de texte extrait ou OCR avant de pouvoir etre classe.',
      aiClassificationFinished: 'Classification IA terminee.',
      aiClassificationFailed: 'La classification IA a echoue.',
      aiClassificationNotSaved: 'La classification IA n a pas ete enregistree.',
      noClassificationSaved: 'Aucune classification semantique enregistree pour ce document.',
      referencesAndCitations: 'References et citations ({outgoing}/{incoming})',
      findReferences: 'Trouver les references',
    },
    referencesPage: {
      title: 'Mes references',
      subtitle: 'Construisez des bibliographies reutilisables pour vos travaux, melangez des documents correspondants et des references libres, puis copiez-les dans votre style prefere.',
      citationStyle: 'Style de citation',
      addWork: 'Ajouter un travail',
      works: 'Travaux',
      worksHelp: 'Choisissez un element de Mon travail ou creez-en un nouveau.',
      selectWork: 'Selectionner un travail',
      referencesCount: '{count} reference{suffix}',
      noWorkSelected: 'Aucun travail selectionne',
      selectWorkToManage: 'Selectionnez un travail pour gerer sa bibliographie.',
      createFirstWork: 'Creez votre premier travail pour commencer a collecter des references.',
      bibliography: 'Bibliographie',
      bibliographyHelp: 'Faites glisser pour reordonner. Copiez n importe quelle entree au format {style}.',
      addReference: 'Ajouter une reference',
      addReferenceDescription: 'Associez un de vos documents quand c est possible, ou enregistrez une reference libre qui n existe que dans cette bibliographie.',
      recheckMatches: 'Reverifier les correspondances',
      loadingReferences: 'Chargement des references...',
      noReferencesYet: 'Aucune reference pour le moment',
      noReferencesYetDescription: 'Ajoutez des references pour construire la bibliographie de ce travail.',
      existsInLibraries: 'Existe dans les bibliotheques',
      copyReference: 'Copier la reference',
      removeReference: 'Supprimer la reference',
      addWorkDescription: 'Creez un element Mon travail pouvant contenir une bibliographie ordonnee.',
      workName: 'Nom du travail',
      workNamePlaceholder: 'Brouillon de mon article',
      createWork: 'Creer le travail',
      deleteWork: 'Supprimer le travail',
      deleteWorkDescription: 'Cela supprimera definitivement "{title}" et ses entrees bibliographiques liees de ce travail.',
      deleteWorkDescriptionFallback: 'Cela supprimera definitivement ce travail et ses entrees bibliographiques liees.',
      cancel: 'Annuler',
      type: 'Type',
      referenceType: 'Type de reference',
      referenceTypeArticle: 'Article',
      referenceTypeBook: 'Livre',
      referenceTypeConference: 'Conference',
      referenceTypeThesis: 'These',
      referenceTypeReport: 'Rapport',
      referenceTypeOnline: 'En ligne',
      referenceTypeMisc: 'Divers',
      referenceTitlePlaceholder: 'Titre de la reference',
      authorsPlaceholder: 'Auteur Un; Auteur Deux',
      publisherSource: 'Editeur / source',
      publisherPlaceholder: 'Editeur',
      journal: 'Revue',
      journalPlaceholder: 'Nom de la revue',
      booktitleCollection: 'Titre du livre / collection',
      booktitlePlaceholder: 'Livre ou actes',
      url: 'URL',
      urlPlaceholder: 'https://example.org',
      abstractNote: 'Resume / note',
      abstractPlaceholder: 'Resume ou note facultative',
      matchingSuggestions: 'Suggestions de correspondance',
      matchingSuggestionsDescription: 'Les documents existants sont suggeres d abord par DOI, puis par titre, auteur et annee.',
      matchingSuggestionsEmpty: 'Saisissez un titre, un DOI ou un auteur pour voir les documents correspondants de votre bibliotheque.',
      matchPercent: 'Correspondance {percent}%',
      alreadyInWork: 'Deja dans ce travail',
      referenceWillBeLinked: 'Cette reference sera liee a un document existant si la correspondance reste valide.',
      freeformReferenceHelp: 'Vous pouvez aussi enregistrer une reference libre sans correspondance.',
      removeReferenceConfirm: 'Supprimer cette reference du travail actuel ?',
      removeReferenceConfirmNamed: 'Supprimer "{title}" de ce travail ?',
      remove: 'Supprimer',
      couldNotLoadReferences: 'Impossible de charger les references.',
      couldNotLoadWorkReferences: 'Impossible de charger les references du travail.',
      selectWorkBeforeAddingReferences: 'Selectionnez un travail avant d ajouter des references.',
      workNameRequired: 'Le nom du travail est obligatoire.',
      createLibraryBeforeAddingWork: 'Creez une bibliotheque avant d ajouter un travail.',
      createdWork: '"{title}" a ete cree.',
      couldNotCreateWork: 'Impossible de creer le travail.',
      deletedWork: '"{title}" a ete supprime.',
      couldNotDeleteWork: 'Impossible de supprimer le travail.',
      addedDocumentToWork: '"{title}" a ete ajoute a ce travail.',
      couldNotAddReference: 'Impossible d ajouter la reference.',
      referenceTitleRequired: 'Le titre de la reference est obligatoire.',
      referenceAdded: 'Reference ajoutee.',
      couldNotCopyReference: 'Impossible de copier la reference.',
      referenceRemovedFromWork: 'Reference supprimee de ce travail.',
      couldNotRemoveReference: 'Impossible de supprimer la reference.',
      referenceMatchesRefreshed: 'Correspondances des references actualisees.',
      couldNotRefreshMatches: 'Impossible d actualiser les correspondances.',
      couldNotReorderReferences: 'Impossible de reordonner les references.',
    },
    mapsPage: {
      title: 'Cartes',
      subtitle: 'Explorez les relations, organisez les vues enregistrées et créez des liens directement sur le canevas.',
      workspace: 'Espace de travail',
      workingMap: 'Choisir une carte',
      workingMapDescription: 'Choisissez une des cartes enregistrées de cette bibliothèque.',
      mapView: 'Vue de la carte',
      canvasEditor: 'Éditeur du canevas',
      addReferencedDocument: 'Ajouter un document référencé',
      addCitingDocument: 'Ajouter un document citant',
      addDocument: 'Ajouter un document',
      addDocumentHelp: 'Recherchez dans la bibliothèque actuelle et ajoutez un autre document à cette carte.',
      addDocumentLinkHelp: 'Recherchez dans la bibliothèque, ajoutez le document au canevas et reliez-le en une seule étape.',
      findReferencedDocument: 'Trouver le document référencé',
      findCitingDocument: 'Trouver le document citant',
      addDocumentToMap: 'Ajouter un document à la carte',
      myWork: 'Mon travail',
      noDocumentsControls: 'Aucun document ne correspond aux contrôles actuels.',
      noLinksControls: 'Aucun lien ne correspond aux contrôles actuels.',
      saveGraphView: 'Enregistrer la vue',
      saveGraphViewDescription: 'Enregistrez la carte actuelle comme espace réutilisable avec ses filtres, son sous-ensemble et sa disposition.',
      editGraphView: 'Modifier la vue',
      editGraphViewDescription: 'Renommez cet espace ou mettez sa description à jour sans changer les relations des documents.',
      cancel: 'Annuler',
      saveView: 'Enregistrer la vue',
      saveChanges: 'Enregistrer les modifications',
      saveAsNewView: 'Enregistrer comme nouvelle vue',
      saveCurrentView: 'Enregistrer les modifications',
      saveCurrentViewHelp: 'Mettre à jour la vue enregistrée actuellement sélectionnée',
      saveNewViewHelp: 'Enregistrer cette disposition et ces filtres comme nouvelle vue réutilisable',
      newMap: 'Nouvelle carte',
      rebuildLayout: 'Reconstruire la disposition',
      rebuildLayoutHelp: 'Répartir les nœuds visibles pour améliorer la disposition',
      deleteMap: 'Supprimer la carte',
      showControls: 'Afficher les contrôles',
      hideControls: 'Masquer les contrôles',
      renameView: 'Renommer la vue',
      duplicateView: 'Dupliquer',
      resetLayout: 'Réinitialiser la disposition',
      resetLayoutHelp: 'Réinitialiser la position des nœuds dans cette vue enregistrée',
      delete: 'Supprimer',
      addMyWork: 'Ajouter "mon travail"',
      noWorksRegisteredPrefix: 'Aucun travail enregistre, allez dans',
      noWorksRegisteredSuffix: 'pour creer un nouveau travail',
      selectWork: 'Selectionner un travail',
      addMyWorkDescription: "Créez un nœud pour votre propre travail. Il est enregistré dans la bibliothèque et peut référencer d'autres documents.",
      addToMap: 'Ajouter à la carte',
      workName: 'Nom du travail',
      workNamePlaceholder: "Mon brouillon d'article",
      name: 'Nom',
      workspaceNote: "Note de l'espace",
      workspaceNotePlaceholder: "Pourquoi cette carte existe, ce que signifie ce sous-ensemble ou ce qu'il faut revoir ensuite.",
      searchDocumentsPlaceholder: 'Rechercher des documents...',
      searchAndLinkPlaceholder: 'Rechercher et ajouter un document à relier...',
      noMatchingDocument: 'Aucun document correspondant trouvé.',
      selectReferenceTarget: "Sélectionnez le document auquel celui-ci fait référence, ou recherchez-le pour l'ajouter",
      selectCitationTarget: "Sélectionnez le document qui fait référence à celui-ci, ou recherchez-le pour l'ajouter",
      deleteNode: 'Masquer le nœud',
      deleteAllLinks: 'Supprimer tous les liens',
      removeLinkMenu: 'Rompre le lien',
      invertLinkMenu: 'Inverser le lien',
      relationDetails: 'Détails de la relation',
      relationDetailsDescription: "Sélectionnez un document pour l'inspecter ou cliquez sur une connexion pour revoir ou supprimer la relation.",
      relation: 'Relation',
      relationDescription: 'Examinez ce lien enregistré entre deux documents.',
      closeDetails: 'Fermer les détails',
      citingDocument: 'Document citant',
      referencedDocument: 'Document référencé',
      makesReferenceTo: 'Fait référence à',
      isReferencedBy: 'Est référencé par',
      reverseLinkDirection: 'Inverser la direction du lien',
      reverseLinkDirectionHelp: "Échanger le document qui pointe vers l'autre",
      breakLink: 'Rompre le lien',
      breakLinkHelp: 'Supprimer définitivement cette relation entre les deux documents',
      otherLinks: 'Autres liens',
      hideFromMap: 'Masquer',
      physicalBook: 'Livre physique',
      myWorkType: 'Mon travail',
      pdfDocument: 'Document PDF',
      author: 'Auteur',
      abstract: 'Résumé',
      collapse: 'Réduire',
      expand: 'Développer',
      none: 'aucun',
      addOrConnect: 'Ajouter ou connecter des documents liés',
      addReference: 'Ajouter une référence',
      addReferenceHelp: 'Relier ce document à celui auquel il fait référence',
      addCitation: 'Ajouter une citation',
      addCitationHelp: 'Relier un document qui cite celui-ci',
      findDocument: 'Trouver un document',
      findDocumentHelp: 'Recherchez dans cette carte et sautez vers un nœud correspondant.',
      searchTitlesInMap: 'Rechercher des titres dans cette carte',
      jumpToMatchingDocument: 'Aller au document correspondant',
      filterLayout: 'Filtres et disposition',
      filterLayoutHelp: 'Afficher les filtres, les options de disposition et les outils rapides',
      expandControls: 'Développer',
      collapseControls: 'Réduire',
      appearance: 'Apparence',
      appearanceDescription: 'Contrôlez l\'apparence des documents dans la carte.',
      nodeColors: 'Couleurs des nœuds',
      libraryColors: 'Bibliothèque',
      yearColors: 'Année',
      density: 'Densité',
      status: 'Statut',
      component: 'Composant',
      nodeSize: 'Taille du nœud',
      uniform: 'Uniforme',
      inboundCitations: 'Citations entrantes',
      totalDegree: 'Degré total',
      focus: 'Focus',
      focusDescription: 'Limitez la vue autour du document sélectionné.',
      focusType: 'Type de focus',
      fullGraph: 'Graphe complet',
      oneHopNeighbors: 'Voisins à 1 saut',
      twoHopNeighbors: 'Voisins à 2 sauts',
      hideIsolated: 'Masquer les documents isolés',
      hideIsolatedDescription: 'Retirer les documents sans liens visibles.',
      years: 'Années',
      yearsDescription: 'Filtrez les documents visibles par année de publication.',
      from: 'De',
      to: 'À',
      any: 'Toutes',
    },
    metadataFields: {
      title: 'Titre',
      authors: 'Auteurs',
      year: 'Année',
      doi: 'DOI',
      isbn: 'ISBN',
      publisher: 'Éditeur',
      citationKey: 'Clé de citation',
      abstract: 'Résumé',
      untitledDocument: 'Document sans titre',
      queuePosition: '{current} sur {total}',
      allCompleteDescription: 'Tous les documents avec DOI dans {library} semblent complets.',
      noMissingDescription: "Aucun document sans option de recherche DOI n'attend dans {library}.",
    },
    common: {
      previous: 'Précédente',
      next: 'Suivante',
      goToPreviousPage: 'Aller à la page précédente',
      goToNextPage: 'Aller à la page suivante',
      currentPage: 'Page actuelle',
      morePages: 'Plus de pages',
      unread: 'Non lu',
      reading: 'En lecture',
      finished: 'Terminé',
      missing: 'Manquant',
      partial: 'Partiel',
      complete: 'Complet',
      ocrPending: 'OCR en attente',
      processing: 'Traitement',
      ocrComplete: 'OCR terminé',
      ocrFailed: 'OCR échoué',
      nativeText: 'Texte natif',
      new: 'NOUVEAU',
    },
    localeNames: {
      en: 'English',
      'pt-BR': 'Português (Brasil)',
      fr: 'Français',
    },
  },
} as const satisfies Record<AppLocale, Record<string, unknown>>

const LocaleContext = createContext<LocaleContextValue>({
  locale: DEFAULT_LOCALE,
  setLocale: () => undefined,
  t: (key) => key,
})

function getNestedValue(source: Record<string, unknown>, key: string): string | undefined {
  return key.split('.').reduce<unknown>((current, part) => {
    if (current && typeof current === 'object' && part in current) {
      return (current as Record<string, unknown>)[part]
    }
    return undefined
  }, source) as string | undefined
}

function interpolate(template: string, params?: TranslationParams) {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`))
}

export function translate(locale: AppLocale, key: string, params?: TranslationParams) {
  const localized = getNestedValue(translations[locale], key)
  const fallback = getNestedValue(translations.en, key)
  return interpolate(localized ?? fallback ?? key, params)
}

export function LocaleProvider({ initialLocale, children }: { initialLocale: AppLocale; children: React.ReactNode }) {
  const [locale, setLocale] = useState<AppLocale>(initialLocale)

  useEffect(() => {
    setLocale(initialLocale)
  }, [initialLocale])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const listener = (event: Event) => {
      const detail = (event as CustomEvent<StoredAppSettings>).detail
      if (detail?.locale) setLocale(detail.locale)
    }
    window.addEventListener('refx-settings-changed', listener)
    return () => window.removeEventListener('refx-settings-changed', listener)
  }, [])

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale
    }
  }, [locale])

  const value = useMemo<LocaleContextValue>(
    () => ({
      locale,
      setLocale,
      t: (key, params) => translate(locale, key, params),
    }),
    [locale],
  )

  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>
}

export function useLocale() {
  return useContext(LocaleContext)
}

export function useT() {
  return useContext(LocaleContext).t
}

export const APP_LOCALES: AppLocale[] = ['en', 'pt-BR', 'fr']
