import type {
  Library,
  Document,
  Author,
  Tag,
  Annotation,
  Note,
  Reference,
  SavedSearch,
  TopicCluster,
  LibraryStats,
  GraphNode,
  GraphEdge,
} from './types'

// Libraries
export const mockLibraries: Library[] = [
  {
    id: 'lib-1',
    name: 'Machine Learning Research',
    description: 'Papers on deep learning, neural networks, and AI',
    color: '#3B82F6',
    icon: 'brain',
    type: 'local',
    documentCount: 247,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-03-20'),
  },
  {
    id: 'lib-2',
    name: 'Climate Science',
    description: 'Environmental research and climate modeling',
    color: '#10B981',
    icon: 'leaf',
    type: 'local',
    documentCount: 89,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2025-03-18'),
  },
  {
    id: 'lib-3',
    name: 'Shared - Team Project',
    description: 'Collaborative literature review',
    color: '#F59E0B',
    icon: 'users',
    type: 'shared',
    documentCount: 156,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2025-03-22'),
  },
  {
    id: 'lib-4',
    name: 'PhD Thesis',
    description: 'Core papers for dissertation',
    color: '#8B5CF6',
    icon: 'graduation-cap',
    type: 'local',
    documentCount: 312,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2025-03-24'),
  },
]

// Documents
export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    libraryId: 'lib-1',
    title: 'Attention Is All You Need',
    subtitle: 'Introducing the Transformer Architecture',
    abstract: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones', 'Aidan N. Gomez', 'Łukasz Kaiser', 'Illia Polosukhin'],
    year: 2017,
    venue: 'NeurIPS 2017',
    doi: '10.48550/arXiv.1706.03762',
    url: 'https://arxiv.org/abs/1706.03762',
    citationKey: 'vaswani2017attention',
    filePath: '/papers/vaswani2017attention.pdf',
    pageCount: 15,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'verified',
    readingStage: 'read',
    rating: 5,
    favorite: true,
    tags: ['transformers', 'attention', 'deep-learning', 'nlp'],
    annotationCount: 24,
    notesCount: 3,
    addedAt: new Date('2024-02-10'),
    lastOpenedAt: new Date('2025-03-20'),
    lastReadPage: 15,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2025-03-20'),
  },
  {
    id: 'doc-2',
    libraryId: 'lib-1',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    abstract: 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.',
    authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
    year: 2019,
    venue: 'NAACL 2019',
    doi: '10.18653/v1/N19-1423',
    citationKey: 'devlin2019bert',
    filePath: '/papers/devlin2019bert.pdf',
    pageCount: 16,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'verified',
    readingStage: 'read',
    rating: 5,
    favorite: true,
    tags: ['bert', 'transformers', 'nlp', 'pre-training'],
    annotationCount: 18,
    notesCount: 2,
    addedAt: new Date('2024-02-15'),
    lastOpenedAt: new Date('2025-03-18'),
    lastReadPage: 16,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2025-03-18'),
  },
  {
    id: 'doc-3',
    libraryId: 'lib-1',
    title: 'GPT-4 Technical Report',
    abstract: 'We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs. While less capable than humans in many real-world scenarios, GPT-4 exhibits human-level performance on various professional and academic benchmarks.',
    authors: ['OpenAI'],
    year: 2023,
    venue: 'arXiv',
    doi: '10.48550/arXiv.2303.08774',
    citationKey: 'openai2023gpt4',
    filePath: '/papers/openai2023gpt4.pdf',
    pageCount: 100,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'complete',
    readingStage: 'reading',
    rating: 4,
    favorite: true,
    tags: ['gpt', 'large-language-models', 'multimodal'],
    annotationCount: 12,
    notesCount: 1,
    addedAt: new Date('2024-03-20'),
    lastOpenedAt: new Date('2025-03-22'),
    lastReadPage: 45,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2025-03-22'),
  },
  {
    id: 'doc-4',
    libraryId: 'lib-1',
    title: 'Deep Residual Learning for Image Recognition',
    abstract: 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously.',
    authors: ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren', 'Jian Sun'],
    year: 2016,
    venue: 'CVPR 2016',
    doi: '10.1109/CVPR.2016.90',
    citationKey: 'he2016deep',
    filePath: '/papers/he2016deep.pdf',
    pageCount: 12,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'verified',
    readingStage: 'read',
    rating: 5,
    favorite: false,
    tags: ['computer-vision', 'resnet', 'deep-learning'],
    annotationCount: 8,
    notesCount: 1,
    addedAt: new Date('2024-01-20'),
    lastOpenedAt: new Date('2025-02-15'),
    lastReadPage: 12,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: 'doc-5',
    libraryId: 'lib-1',
    title: 'Scaling Laws for Neural Language Models',
    abstract: 'We study empirical scaling laws for language model performance on the cross-entropy loss. The loss scales as a power-law with model size, dataset size, and the amount of compute used for training, with some trends spanning more than seven orders of magnitude.',
    authors: ['Jared Kaplan', 'Sam McCandlish', 'Tom Henighan', 'Tom B. Brown', 'Benjamin Chess', 'Rewon Child', 'Scott Gray', 'Alec Radford', 'Jeffrey Wu', 'Dario Amodei'],
    year: 2020,
    venue: 'arXiv',
    doi: '10.48550/arXiv.2001.08361',
    citationKey: 'kaplan2020scaling',
    pageCount: 26,
    hasOcr: false,
    ocrStatus: 'pending',
    metadataStatus: 'partial',
    readingStage: 'unread',
    rating: 0,
    favorite: false,
    tags: ['scaling-laws', 'large-language-models'],
    annotationCount: 0,
    notesCount: 0,
    addedAt: new Date('2025-03-15'),
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-03-15'),
  },
  {
    id: 'doc-6',
    libraryId: 'lib-2',
    title: 'Climate Change 2021: The Physical Science Basis',
    abstract: 'This report addresses the most up-to-date physical understanding of the climate system and climate change, bringing together the latest advances in climate science.',
    authors: ['IPCC Working Group I'],
    year: 2021,
    venue: 'IPCC Sixth Assessment Report',
    citationKey: 'ipcc2021physical',
    filePath: '/papers/ipcc2021physical.pdf',
    pageCount: 3949,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'complete',
    readingStage: 'skimmed',
    rating: 4,
    favorite: true,
    tags: ['climate-change', 'ipcc', 'physical-science'],
    annotationCount: 45,
    notesCount: 5,
    addedAt: new Date('2024-05-10'),
    lastOpenedAt: new Date('2025-03-10'),
    lastReadPage: 120,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: 'doc-7',
    libraryId: 'lib-2',
    title: 'Global Carbon Budget 2024',
    abstract: 'Accurate assessment of anthropogenic carbon dioxide (CO2) emissions and their redistribution among the atmosphere, ocean, and terrestrial biosphere is important to better understand the global carbon cycle.',
    authors: ['Pierre Friedlingstein', 'Michael O\'Sullivan', 'Matthew W. Jones'],
    year: 2024,
    venue: 'Earth System Science Data',
    doi: '10.5194/essd-16-2625-2024',
    citationKey: 'friedlingstein2024global',
    pageCount: 86,
    hasOcr: false,
    ocrStatus: 'pending',
    metadataStatus: 'incomplete',
    readingStage: 'unread',
    rating: 0,
    favorite: false,
    tags: ['carbon-budget', 'emissions', 'climate'],
    annotationCount: 0,
    notesCount: 0,
    addedAt: new Date('2025-03-22'),
    createdAt: new Date('2025-03-22'),
    updatedAt: new Date('2025-03-22'),
  },
  {
    id: 'doc-8',
    libraryId: 'lib-4',
    title: 'Neural Machine Translation by Jointly Learning to Align and Translate',
    abstract: 'Neural machine translation is a recently proposed approach to machine translation. In this paper, we conjecture that the use of a fixed-length vector is a bottleneck in improving the performance of this basic encoder-decoder architecture.',
    authors: ['Dzmitry Bahdanau', 'Kyunghyun Cho', 'Yoshua Bengio'],
    year: 2015,
    venue: 'ICLR 2015',
    doi: '10.48550/arXiv.1409.0473',
    citationKey: 'bahdanau2015neural',
    filePath: '/papers/bahdanau2015neural.pdf',
    pageCount: 15,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'verified',
    readingStage: 'read',
    rating: 5,
    favorite: true,
    tags: ['attention', 'machine-translation', 'seq2seq'],
    annotationCount: 15,
    notesCount: 2,
    addedAt: new Date('2023-09-15'),
    lastOpenedAt: new Date('2025-01-20'),
    lastReadPage: 15,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'doc-9',
    libraryId: 'lib-1',
    title: 'Language Models are Few-Shot Learners',
    abstract: 'Recent work has demonstrated substantial gains on many NLP tasks and benchmarks by pre-training on a large corpus of text followed by fine-tuning on a specific task.',
    authors: ['Tom B. Brown', 'Benjamin Mann', 'Nick Ryder', 'Melanie Subbiah'],
    year: 2020,
    venue: 'NeurIPS 2020',
    doi: '10.48550/arXiv.2005.14165',
    citationKey: 'brown2020language',
    filePath: '/papers/brown2020language.pdf',
    pageCount: 75,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'complete',
    readingStage: 'reading',
    rating: 5,
    favorite: true,
    tags: ['gpt-3', 'few-shot', 'large-language-models'],
    annotationCount: 22,
    notesCount: 3,
    addedAt: new Date('2024-04-01'),
    lastOpenedAt: new Date('2025-03-21'),
    lastReadPage: 50,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2025-03-21'),
  },
  {
    id: 'doc-10',
    libraryId: 'lib-3',
    title: 'A Survey of Large Language Models',
    abstract: 'Ever since the Turing Test was proposed in the 1950s, humans have explored the mastering of language intelligence by machine. Language is essentially a complex, intricate system of human expressions governed by grammatical rules.',
    authors: ['Wayne Xin Zhao', 'Kun Zhou', 'Junyi Li', 'Tianyi Tang'],
    year: 2023,
    venue: 'arXiv',
    doi: '10.48550/arXiv.2303.18223',
    citationKey: 'zhao2023survey',
    pageCount: 124,
    hasOcr: true,
    ocrStatus: 'complete',
    metadataStatus: 'complete',
    readingStage: 'skimmed',
    rating: 4,
    favorite: false,
    tags: ['survey', 'large-language-models', 'nlp'],
    annotationCount: 8,
    notesCount: 1,
    addedAt: new Date('2024-08-15'),
    lastOpenedAt: new Date('2025-03-05'),
    lastReadPage: 60,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2025-03-05'),
  },
]

// Authors
export const mockAuthors: Author[] = [
  { id: 'auth-1', displayName: 'Ashish Vaswani', normalizedName: 'vaswani, ashish', documentCount: 1 },
  { id: 'auth-2', displayName: 'Jacob Devlin', normalizedName: 'devlin, jacob', documentCount: 1 },
  { id: 'auth-3', displayName: 'Kaiming He', normalizedName: 'he, kaiming', orcid: '0000-0002-1234-5678', documentCount: 1 },
  { id: 'auth-4', displayName: 'Yoshua Bengio', normalizedName: 'bengio, yoshua', orcid: '0000-0002-8888-8888', documentCount: 2 },
  { id: 'auth-5', displayName: 'Tom B. Brown', normalizedName: 'brown, tom b.', documentCount: 2 },
]

// Tags
export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'transformers', color: '#3B82F6', type: 'manual', documentCount: 3 },
  { id: 'tag-2', name: 'attention', color: '#8B5CF6', type: 'manual', documentCount: 2 },
  { id: 'tag-3', name: 'deep-learning', color: '#10B981', type: 'manual', documentCount: 4 },
  { id: 'tag-4', name: 'nlp', color: '#F59E0B', type: 'manual', documentCount: 5 },
  { id: 'tag-5', name: 'large-language-models', color: '#EF4444', type: 'auto', documentCount: 4 },
  { id: 'tag-6', name: 'computer-vision', color: '#06B6D4', type: 'manual', documentCount: 2 },
  { id: 'tag-7', name: 'climate-change', color: '#22C55E', type: 'manual', documentCount: 2 },
  { id: 'tag-8', name: 'survey', color: '#A855F7', type: 'auto', documentCount: 1 },
  { id: 'tag-9', name: 'pre-training', color: '#EC4899', type: 'manual', documentCount: 2 },
  { id: 'tag-10', name: 'bert', color: '#14B8A6', type: 'manual', documentCount: 1 },
]

// Annotations
export const mockAnnotations: Annotation[] = [
  {
    id: 'ann-1',
    documentId: 'doc-1',
    type: 'highlight',
    page: 1,
    textQuote: 'The Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
    color: '#FBBF24',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'ann-2',
    documentId: 'doc-1',
    type: 'note',
    page: 3,
    textQuote: 'Multi-Head Attention',
    comment: 'Key innovation - allows the model to jointly attend to information from different representation subspaces at different positions.',
    color: '#34D399',
    createdAt: new Date('2024-03-16'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: 'ann-3',
    documentId: 'doc-1',
    type: 'bookmark',
    page: 5,
    comment: 'Positional encoding formula',
    color: '#60A5FA',
    createdAt: new Date('2024-03-17'),
    updatedAt: new Date('2024-03-17'),
  },
  {
    id: 'ann-4',
    documentId: 'doc-2',
    type: 'highlight',
    page: 2,
    textQuote: 'BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.',
    color: '#FBBF24',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'ann-5',
    documentId: 'doc-3',
    type: 'highlight',
    page: 10,
    textQuote: 'GPT-4 exhibits human-level performance on various professional and academic benchmarks.',
    color: '#F472B6',
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
  },
]

// Notes
export const mockNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Transformer Architecture Overview',
    content: '# Transformer Architecture\n\nThe transformer architecture revolutionized NLP by replacing recurrence with self-attention.\n\n## Key Components\n- Multi-head attention\n- Positional encoding\n- Feed-forward networks\n- Layer normalization\n\n## Impact\nThis architecture forms the basis for BERT, GPT, and most modern LLMs.',
    linkedDocumentIds: ['doc-1', 'doc-2'],
    linkedAnnotationIds: ['ann-1', 'ann-2'],
    tags: ['transformers', 'architecture'],
    pinned: true,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2025-03-15'),
  },
  {
    id: 'note-2',
    title: 'Scaling Laws Summary',
    content: '# Scaling Laws for LLMs\n\nKey findings:\n- Performance scales predictably with compute, data, and model size\n- Power-law relationships hold across many orders of magnitude\n- Optimal allocation of compute suggests training larger models on more data',
    linkedDocumentIds: ['doc-5', 'doc-9'],
    linkedAnnotationIds: [],
    tags: ['scaling', 'large-language-models'],
    pinned: false,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: 'note-3',
    title: 'Climate Modeling Notes',
    content: '# Climate Model Observations\n\n## Key Takeaways from IPCC Report\n- Global surface temperature increased by 1.1°C\n- Human influence is unequivocal\n- Extreme weather events are increasing',
    linkedDocumentIds: ['doc-6'],
    linkedAnnotationIds: [],
    tags: ['climate', 'research-notes'],
    pinned: false,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
  },
]

// References
export const mockReferences: Reference[] = [
  {
    id: 'ref-1',
    documentId: 'doc-1',
    rawBibtex: `@inproceedings{vaswani2017attention,
  title={Attention is all you need},
  author={Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, {\\L}ukasz and Polosukhin, Illia},
  booktitle={Advances in neural information processing systems},
  volume={30},
  year={2017}
}`,
    itemType: 'inproceedings',
    fields: {
      title: 'Attention is all you need',
      author: 'Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, Łukasz and Polosukhin, Illia',
      booktitle: 'Advances in neural information processing systems',
      volume: '30',
      year: '2017',
    },
    doi: '10.48550/arXiv.1706.03762',
    citationKey: 'vaswani2017attention',
    source: 'crossref',
    metadataConfidence: 0.98,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'ref-2',
    documentId: 'doc-2',
    rawBibtex: `@inproceedings{devlin2019bert,
  title={BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding},
  author={Devlin, Jacob and Chang, Ming-Wei and Lee, Kenton and Toutanova, Kristina},
  booktitle={Proceedings of NAACL-HLT},
  year={2019}
}`,
    itemType: 'inproceedings',
    fields: {
      title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
      author: 'Devlin, Jacob and Chang, Ming-Wei and Lee, Kenton and Toutanova, Kristina',
      booktitle: 'Proceedings of NAACL-HLT',
      year: '2019',
    },
    doi: '10.18653/v1/N19-1423',
    citationKey: 'devlin2019bert',
    source: 'crossref',
    metadataConfidence: 0.95,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
]

// Saved Searches
export const mockSavedSearches: SavedSearch[] = [
  {
    id: 'search-1',
    name: 'Recent Transformer Papers',
    query: 'transformer attention',
    filters: { year: { min: 2020 }, tags: ['transformers'] },
    resultCount: 15,
    lastRun: new Date('2025-03-20'),
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'search-2',
    name: 'Unread ML Papers',
    query: '',
    filters: { readingStage: ['unread'], libraryId: 'lib-1' },
    resultCount: 23,
    lastRun: new Date('2025-03-22'),
    createdAt: new Date('2024-08-15'),
  },
  {
    id: 'search-3',
    name: 'Climate Reports',
    query: 'climate IPCC',
    filters: { libraryId: 'lib-2' },
    resultCount: 8,
    lastRun: new Date('2025-03-18'),
    createdAt: new Date('2024-09-01'),
  },
]

// Topic Clusters
export const mockTopicClusters: TopicCluster[] = [
  {
    id: 'topic-1',
    name: 'Large Language Models',
    description: 'Papers covering GPT, BERT, and scaling of language models',
    keywords: ['llm', 'gpt', 'bert', 'transformer', 'pre-training'],
    documentIds: ['doc-1', 'doc-2', 'doc-3', 'doc-9', 'doc-10'],
    color: '#3B82F6',
  },
  {
    id: 'topic-2',
    name: 'Attention Mechanisms',
    description: 'Research on attention and self-attention in neural networks',
    keywords: ['attention', 'self-attention', 'multi-head', 'cross-attention'],
    documentIds: ['doc-1', 'doc-8'],
    color: '#8B5CF6',
  },
  {
    id: 'topic-3',
    name: 'Climate Science',
    description: 'Environmental research and climate projections',
    keywords: ['climate', 'carbon', 'emissions', 'ipcc', 'warming'],
    documentIds: ['doc-6', 'doc-7'],
    color: '#10B981',
  },
]

// Library Stats
export const mockLibraryStats: LibraryStats = {
  totalDocuments: 804,
  totalAnnotations: 156,
  totalNotes: 42,
  byReadingStage: {
    unread: 145,
    reading: 38,
    skimmed: 89,
    read: 478,
    archived: 54,
  },
  byYear: [
    { year: 2015, count: 23 },
    { year: 2016, count: 31 },
    { year: 2017, count: 45 },
    { year: 2018, count: 52 },
    { year: 2019, count: 78 },
    { year: 2020, count: 112 },
    { year: 2021, count: 134 },
    { year: 2022, count: 156 },
    { year: 2023, count: 98 },
    { year: 2024, count: 62 },
    { year: 2025, count: 13 },
  ],
  byTag: [
    { tag: 'deep-learning', count: 234 },
    { tag: 'nlp', count: 189 },
    { tag: 'computer-vision', count: 156 },
    { tag: 'transformers', count: 98 },
    { tag: 'reinforcement-learning', count: 67 },
  ],
  recentlyAdded: 12,
  ocrPending: 23,
  metadataIncomplete: 45,
}

// Graph Data for Maps
export const mockGraphNodes: GraphNode[] = [
  { id: 'node-doc-1', type: 'document', label: 'Attention Is All You Need', data: mockDocuments[0] },
  { id: 'node-doc-2', type: 'document', label: 'BERT', data: mockDocuments[1] },
  { id: 'node-doc-3', type: 'document', label: 'GPT-4 Technical Report', data: mockDocuments[2] },
  { id: 'node-doc-8', type: 'document', label: 'Neural Machine Translation', data: mockDocuments[7] },
  { id: 'node-doc-9', type: 'document', label: 'Few-Shot Learners', data: mockDocuments[8] },
  { id: 'node-topic-1', type: 'topic', label: 'Large Language Models', data: mockTopicClusters[0] },
  { id: 'node-topic-2', type: 'topic', label: 'Attention Mechanisms', data: mockTopicClusters[1] },
  { id: 'node-auth-4', type: 'author', label: 'Yoshua Bengio', data: mockAuthors[3] },
  { id: 'node-tag-1', type: 'tag', label: 'transformers', data: mockTags[0] },
]

export const mockGraphEdges: GraphEdge[] = [
  { id: 'edge-1', source: 'node-doc-1', target: 'node-doc-2', type: 'cites', weight: 1 },
  { id: 'edge-2', source: 'node-doc-2', target: 'node-doc-1', type: 'cites', weight: 1 },
  { id: 'edge-3', source: 'node-doc-3', target: 'node-doc-1', type: 'cites', weight: 1 },
  { id: 'edge-4', source: 'node-doc-3', target: 'node-doc-2', type: 'cites', weight: 1 },
  { id: 'edge-5', source: 'node-doc-8', target: 'node-auth-4', type: 'authored', weight: 1 },
  { id: 'edge-6', source: 'node-doc-1', target: 'node-tag-1', type: 'tagged', weight: 1 },
  { id: 'edge-7', source: 'node-doc-1', target: 'node-topic-2', type: 'related', weight: 0.9 },
  { id: 'edge-8', source: 'node-doc-2', target: 'node-topic-1', type: 'related', weight: 0.85 },
  { id: 'edge-9', source: 'node-doc-9', target: 'node-topic-1', type: 'related', weight: 0.95 },
]

// Helper functions to simulate data operations
export function getDocumentsByLibrary(libraryId: string): Document[] {
  return mockDocuments.filter((doc) => doc.libraryId === libraryId)
}

export function getDocumentById(id: string): Document | undefined {
  return mockDocuments.find((doc) => doc.id === id)
}

export function getAnnotationsByDocument(documentId: string): Annotation[] {
  return mockAnnotations.filter((ann) => ann.documentId === documentId)
}

export function getRecentDocuments(limit: number = 5): Document[] {
  return [...mockDocuments]
    .sort((a, b) => (b.lastOpenedAt?.getTime() || 0) - (a.lastOpenedAt?.getTime() || 0))
    .slice(0, limit)
}

export function getContinueReading(): Document[] {
  return mockDocuments
    .filter((doc) => doc.readingStage === 'reading' && doc.lastReadPage)
    .sort((a, b) => (b.lastOpenedAt?.getTime() || 0) - (a.lastOpenedAt?.getTime() || 0))
}

export function getDocumentsNeedingMetadata(): Document[] {
  return mockDocuments.filter((doc) => doc.metadataStatus === 'incomplete' || doc.metadataStatus === 'partial')
}

export function getOcrPendingDocuments(): Document[] {
  return mockDocuments.filter((doc) => doc.ocrStatus === 'pending')
}
